// Code generated by gomacro/typescript/axios_api.go. DO NOT EDIT

import type { AxiosResponse } from "axios";
import Axios from "axios";

// AAAA-MM-YY date format
export type Date_ = string & { __opaque__: "Date" };

export type Int = number & { __opaque__: "Int" };
// registro/controllers/inscriptions.CampExt
export interface CampExt {
  Id: IdCamp;
  Nom: string;
  DateDebut: Date;
  Duree: Int;
  Lieu: string;
  Description: string;
  Navette: OptionNavette;
  Places: Int;
  AgeMin: Int;
  AgeMax: Int;
  Prix: string;
  Direction: string;
}
// registro/controllers/inscriptions.Data
export interface Data {
  Camps: CampExt[] | null;
  InitialInscription: Inscription;
  Settings: Settings;
}
// registro/controllers/inscriptions.Inscription
export interface Inscription {
  Responsable: ResponsableLegal;
  Message: string;
  CopiesMails: Mails;
  PartageAdressesOK: boolean;
  DemandeFondSoutien: boolean;
  Participants: Participant[] | null;
}
// registro/controllers/inscriptions.Participant
export interface Participant {
  IdCamp: IdCamp;
  Nom: string;
  Prenom: string;
  DateNaissance: Date;
  Sexe: Sexe;
  Nationnalite: Nationnalite;
}
// registro/controllers/inscriptions.SearchHistoryOut
export interface SearchHistoryOut {
  MailFound: boolean;
}
// registro/controllers/inscriptions.Settings
export interface Settings {
  PreselectedCamp: IdCamp;
  SupportBonsCAF: boolean;
  SupportANCV: boolean;
  EmailRetraitMedia: string;
  ShowFondSoutien: boolean;
  ShowCharteConduite: boolean;
}
export type IdCamp = number & { __opaque__: "IdCamp" };
// registro/sql/camps.OptionNavette
export interface OptionNavette {
  Actif: boolean;
  Commentaire: string;
}
// registro/sql/inscriptions.ResponsableLegal
export interface ResponsableLegal {
  Nom: string;
  Prenom: string;
  DateNaissance: Date;
  Sexe: Sexe;
  Mail: string;
  Tels: Tels;
  Adresse: string;
  CodePostal: string;
  Ville: string;
  Pays: Pays;
}
// registro/sql/personnes.Mails
export type Mails = string[] | null;
// registro/sql/personnes.Nationnalite
export const Nationnalite = {
  Autre: 0,
  Francaise: 1,
  Suisse: 2,
} as const;
export type Nationnalite = (typeof Nationnalite)[keyof typeof Nationnalite];

export const NationnaliteLabels: Record<Nationnalite, string> = {
  [Nationnalite.Autre]: "Autre",
  [Nationnalite.Francaise]: "Française",
  [Nationnalite.Suisse]: "Suisse",
};

// registro/sql/personnes.Pays
export type Pays = string;
// registro/sql/personnes.Sexe
export const Sexe = {
  Empty: 0,
  Woman: 1,
  Man: 2,
} as const;
export type Sexe = (typeof Sexe)[keyof typeof Sexe];

export const SexeLabels: Record<Sexe, string> = {
  [Sexe.Empty]: "",
  [Sexe.Woman]: "Femme",
  [Sexe.Man]: "Homme",
};

// registro/sql/personnes.Tels
export type Tels = string[] | null;
// registro/sql/shared.Date
export type Date = Date_;

/** AbstractAPI provides auto-generated API calls and should be used 
		as base class for an app controller.
	*/
export abstract class AbstractAPI {
  constructor(
    protected baseUrl: string,
    protected authToken: string,
  ) {}

  protected abstract handleError(error: any): void;

  protected abstract startRequest(): void;

  getHeaders() {
    return { Authorization: "Bearer " + this.authToken };
  }

  /** LoadData performs the request and handles the error */
  async LoadData(params: { preselected: IdCamp; preinscription: string }) {
    const fullUrl = this.baseUrl + "/api/v1/inscription/load";
    this.startRequest();
    try {
      const rep: AxiosResponse<Data> = await Axios.get(fullUrl, {
        headers: this.getHeaders(),
        params: {
          preselected: String(params["preselected"]),
          preinscription: params["preinscription"],
        },
      });
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** SaveInscription performs the request and handles the error */
  async SaveInscription(params: Inscription) {
    const fullUrl = this.baseUrl + "/api/v1/inscription/save";
    this.startRequest();
    try {
      await Axios.put(fullUrl, params, { headers: this.getHeaders() });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** SearchHistory performs the request and handles the error */
  async SearchHistory(params: { mail: string }) {
    const fullUrl = this.baseUrl + "/api/v1/inscription/search";
    this.startRequest();
    try {
      const rep: AxiosResponse<SearchHistoryOut> = await Axios.get(fullUrl, {
        headers: this.getHeaders(),
        params: { mail: params["mail"] },
      });
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }
}
