// Code generated by gomacro/typescript/axios_api.go. DO NOT EDIT

import type { AxiosResponse } from "axios";
import Axios from "axios";

// AAAA-MM-YY date format
export type Date_ = string & { __opaque__: "Date" };

export type Int = number & { __opaque__: "Int" };
// registro/controllers/dons.DonExt
export interface DonExt {
  Don: Don;
  Montant: string;
  Donateur: string;
}
// registro/controllers/dons.DonsOut
export interface DonsOut {
  Dons: DonExt[] | null;
  YearTotals: Record<Int, YearTotal> | null;
}
// registro/controllers/dons.LogginOut
export interface LogginOut {
  IsValid: boolean;
  Token: string;
}
// registro/controllers/dons.OrganismeHeader
export interface OrganismeHeader {
  Id: IdOrganisme;
  Nom: string;
}
// registro/controllers/dons.YearTotal
export interface YearTotal {
  Particuliers: string;
  Organismes: string;
}
// registro/logic/search.PersonneHeader
export interface PersonneHeader {
  Id: IdPersonne;
  Label: string;
  Sexe: Sexe;
  DateNaissance: Date;
  IsTemp: boolean;
}
// registro/sql/dons.Don
export interface Don {
  Id: IdDon;
  IdPersonne: OptID_IdPersonne;
  IdOrganisme: OptID_IdOrganisme;
  Montant: Montant;
  ModePaiement: ModePaiement;
  Date: Date;
  Affectation: string;
  Details: string;
  Remercie: boolean;
}
export type IdDon = Int & { __opaque_int__: "IdDon" };
export type IdOrganisme = Int & { __opaque_int__: "IdOrganisme" };
// registro/sql/dossiers.Currency
export const Currency = {
  Euros: 0,
  FrancsSuisse: 1,
} as const;
export type Currency = (typeof Currency)[keyof typeof Currency];

export const CurrencyLabels: Record<Currency, string> = {
  [Currency.Euros]: "€",
  [Currency.FrancsSuisse]: "CHF",
};

// registro/sql/dossiers.ModePaiement
export const ModePaiement = {
  Cheque: 0,
  EnLigne: 1,
  Virement: 2,
  Especes: 3,
  Ancv: 4,
  Helloasso: 5,
} as const;
export type ModePaiement = (typeof ModePaiement)[keyof typeof ModePaiement];

export const ModePaiementLabels: Record<ModePaiement, string> = {
  [ModePaiement.Cheque]: "Chèque",
  [ModePaiement.EnLigne]: "Carte bancaire (en ligne)",
  [ModePaiement.Virement]: "Virement",
  [ModePaiement.Especes]: "Espèces",
  [ModePaiement.Ancv]: "ANCV",
  [ModePaiement.Helloasso]: "Helloasso",
};

// registro/sql/dossiers.Montant
export interface Montant {
  Cent: Int;
  Currency: Currency;
}
export type IdPersonne = Int & { __opaque_int__: "IdPersonne" };
// registro/sql/personnes.Sexe
export const Sexe = {
  NoSexe: 0,
  Woman: 1,
  Man: 2,
} as const;
export type Sexe = (typeof Sexe)[keyof typeof Sexe];

export const SexeLabels: Record<Sexe, string> = {
  [Sexe.NoSexe]: "",
  [Sexe.Woman]: "Femme",
  [Sexe.Man]: "Homme",
};

// registro/sql/shared.Date
export type Date = Date_;
// registro/sql/shared.OptID[registro/sql/dons.IdOrganisme]
export interface OptID_IdOrganisme {
  Id: IdOrganisme;
  Valid: boolean;
}
// registro/sql/shared.OptID[registro/sql/personnes.IdPersonne]
export interface OptID_IdPersonne {
  Id: IdPersonne;
  Valid: boolean;
}

/** AbstractAPI provides auto-generated API calls and should be used 
		as base class for an app controller.
	*/
export abstract class AbstractAPI {
  constructor(
    protected baseURL: string,
    public authToken: string,
  ) {}

  protected abstract handleError(error: any): void;

  protected abstract startRequest(): void;

  getHeaders() {
    return { Authorization: "Bearer " + this.authToken };
  }

  /** Loggin performs the request and handles the error */
  async Loggin(params: { password: string }) {
    const fullUrl = this.baseURL + "/api/v1/loggin";
    this.startRequest();
    try {
      const rep: AxiosResponse<LogginOut> = await Axios.get(fullUrl, {
        headers: this.getHeaders(),
        params: { password: params["password"] },
      });
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** LoadDons performs the request and handles the error */
  async LoadDons() {
    const fullUrl = this.baseURL + "/api/v1/dons";
    this.startRequest();
    try {
      const rep: AxiosResponse<DonsOut> = await Axios.get(fullUrl, {
        headers: this.getHeaders(),
      });
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** UpdateDon performs the request and handles the error */
  async UpdateDon(params: Don) {
    const fullUrl = this.baseURL + "/api/v1/dons";
    this.startRequest();
    try {
      await Axios.post(fullUrl, params, { headers: this.getHeaders() });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** CreateDon performs the request and handles the error */
  async CreateDon(params: Don) {
    const fullUrl = this.baseURL + "/api/v1/dons";
    this.startRequest();
    try {
      const rep: AxiosResponse<Don> = await Axios.put(fullUrl, params, {
        headers: this.getHeaders(),
      });
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** DeleteDon performs the request and handles the error */
  async DeleteDon(params: { id: IdDon }) {
    const fullUrl = this.baseURL + "/api/v1/dons";
    this.startRequest();
    try {
      await Axios.delete(fullUrl, {
        headers: this.getHeaders(),
        params: { id: String(params["id"]) },
      });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** SearchPersonnes performs the request and handles the error */
  async SearchPersonnes(params: { search: string }) {
    const fullUrl = this.baseURL + "/api/v1/dons/search-personnes";
    this.startRequest();
    try {
      const rep: AxiosResponse<PersonneHeader[] | null> = await Axios.get(
        fullUrl,
        { headers: this.getHeaders(), params: { search: params["search"] } },
      );
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** SearchOrganismes performs the request and handles the error */
  async SearchOrganismes(params: { search: string }) {
    const fullUrl = this.baseURL + "/api/v1/dons/search-organismes";
    this.startRequest();
    try {
      const rep: AxiosResponse<OrganismeHeader[] | null> = await Axios.get(
        fullUrl,
        { headers: this.getHeaders(), params: { search: params["search"] } },
      );
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** Returns an URL with method GET */
  DownloadRecusFiscaux(year: Int, token: string) {
    return (
      this.baseURL +
      "/api/v1/dons/download-recus-fiscaux" +
      `?year=${year}&token=${token}`
    );
  }

  /** Returns an URL with method GET */
  DownloadDonsExcel(year: Int, token: string) {
    return (
      this.baseURL +
      "/api/v1/dons/download-dons" +
      `?year=${year}&token=${token}`
    );
  }
}
