package camps

import (
	"math/rand"
	"registro/sql/personnes"
	"time"
)

// Code generated by gomacro/generator/go/randdata. DO NOT EDIT.

func randCamp() Camp {
	var s Camp
	s.Id = randIdCamp()
	s.Nom = randstring()
	s.DateDebut = randper_Date()
	s.Duree = randint()
	s.Agrement = randstring()

	return s
}

func randIdCamp() IdCamp {
	return IdCamp(randint64())
}

func randIdParticipant() IdParticipant {
	return IdParticipant(randint64())
}

func randParticipant() Participant {
	var s Participant
	s.Id = randIdParticipant()
	s.IdCamp = randIdCamp()
	s.IdPersonne = randper_IdPersonne()

	return s
}

func randint() int {
	return int(rand.Intn(1000000))
}

func randint64() int64 {
	return int64(rand.Intn(1000000))
}

func randper_Date() personnes.Date {
	return personnes.Date(randtTime())
}

func randper_IdPersonne() personnes.IdPersonne {
	return personnes.IdPersonne(randint64())
}

var letterRunes2 = []rune("azertyuiopqsdfghjklmwxcvbn123456789é@!?&èïab ")

func randstring() string {
	b := make([]rune, 10)
	maxLength := len(letterRunes2)
	for i := range b {
		b[i] = letterRunes2[rand.Intn(maxLength)]
	}
	return string(b)
}

func randtTime() time.Time {
	return time.Unix(int64(rand.Int31()), 5)
}
