package camps

import "encoding/json"

// Code generated by gomacro/generator/gounions. DO NOT EDIT

// ChampQuestionWrapper may be used as replacements for ChampQuestion
// when working with JSON
type ChampQuestionWrapper struct {
	Data ChampQuestion
}

func (out *ChampQuestionWrapper) UnmarshalJSON(src []byte) error {
	var wr struct {
		Kind string
		Data json.RawMessage
	}
	err := json.Unmarshal(src, &wr)
	if err != nil {
		return err
	}
	switch wr.Kind {
	case "ChampQCM":
		var data ChampQCM
		err = json.Unmarshal(wr.Data, &data)
		out.Data = data
	case "ChampTexte":
		var data ChampTexte
		err = json.Unmarshal(wr.Data, &data)
		out.Data = data

	default:
		panic("exhaustive switch")
	}
	return err
}

func (item ChampQuestionWrapper) MarshalJSON() ([]byte, error) {
	type wrapper struct {
		Data any
		Kind string
	}
	var wr wrapper
	switch data := item.Data.(type) {
	case ChampQCM:
		wr = wrapper{Kind: "ChampQCM", Data: data}
	case ChampTexte:
		wr = wrapper{Kind: "ChampTexte", Data: data}

	default:
		panic("exhaustive switch")
	}
	return json.Marshal(wr)
}

const (
	ChampQCMChKind   = "ChampQCM"
	ChampTexteChKind = "ChampTexte"
)

// ChampReponseWrapper may be used as replacements for ChampReponse
// when working with JSON
type ChampReponseWrapper struct {
	Data ChampReponse
}

func (out *ChampReponseWrapper) UnmarshalJSON(src []byte) error {
	var wr struct {
		Kind string
		Data json.RawMessage
	}
	err := json.Unmarshal(src, &wr)
	if err != nil {
		return err
	}
	switch wr.Kind {
	case "ChampReponseQCM":
		var data ChampReponseQCM
		err = json.Unmarshal(wr.Data, &data)
		out.Data = data
	case "ChampReponseTexte":
		var data ChampReponseTexte
		err = json.Unmarshal(wr.Data, &data)
		out.Data = data

	default:
		panic("exhaustive switch")
	}
	return err
}

func (item ChampReponseWrapper) MarshalJSON() ([]byte, error) {
	type wrapper struct {
		Data any
		Kind string
	}
	var wr wrapper
	switch data := item.Data.(type) {
	case ChampReponseQCM:
		wr = wrapper{Kind: "ChampReponseQCM", Data: data}
	case ChampReponseTexte:
		wr = wrapper{Kind: "ChampReponseTexte", Data: data}

	default:
		panic("exhaustive switch")
	}
	return json.Marshal(wr)
}

const (
	ChampReponseQCMChKind   = "ChampReponseQCM"
	ChampReponseTexteChKind = "ChampReponseTexte"
)

func (item Champ) MarshalJSON() ([]byte, error) {
	type wrapper struct {
		Titre       string
		Description string
		Question    ChampQuestionWrapper
	}
	wr := wrapper{
		Titre:       item.Titre,
		Description: item.Description,
		Question:    ChampQuestionWrapper{item.Question},
	}
	return json.Marshal(wr)
}

func (item *Champ) UnmarshalJSON(src []byte) error {
	type wrapper struct {
		Titre       string
		Description string
		Question    ChampQuestionWrapper
	}
	var wr wrapper
	err := json.Unmarshal(src, &wr)
	if err != nil {
		return err
	}
	item.Titre = wr.Titre
	item.Description = wr.Description
	item.Question = wr.Question.Data
	return nil
}

func (list FormReponses) MarshalJSON() ([]byte, error) {
	tmp := make([]ChampReponseWrapper, len(list))
	for i, v := range list {
		tmp[i].Data = v
	}
	return json.Marshal(tmp)
}

func (list *FormReponses) UnmarshalJSON(data []byte) error {
	var tmp []ChampReponseWrapper
	err := json.Unmarshal(data, &tmp)
	*list = make(FormReponses, len(tmp))
	for i, v := range tmp {
		(*list)[i] = v.Data
	}
	return err
}
