// Code generated by gomacro/typescript/axios_api.go. DO NOT EDIT

import type { AxiosResponse } from "axios";
import Axios from "axios";

/** AbstractAPI provides auto-generated API calls and should be used 
		as base class for an app controller.
	*/
export abstract class AbstractAPI {
  constructor(
    protected baseURL: string,
    public authToken: string,
  ) {}

  protected abstract handleError(error: any): void;

  protected abstract startRequest(): void;

  getHeaders() {
    return { Authorization: "Bearer " + this.authToken };
  }

  /** ValideTransfertFicheSanitaire performs the request and handles the error */
  async ValideTransfertFicheSanitaire(params: { token: string }) {
    const fullUrl =
      this.baseURL + "/api/v1/espaceperso/fichesanitaires/transfert";
    this.startRequest();
    try {
      await Axios.post(fullUrl, null, {
        headers: this.getHeaders(),
        params: { token: params["token"] },
      });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }
}
