// Code generated by gomacro/generator/typescript. DO NOT EDIT.
// registro/controllers/services.Service
export const Service = {
  TransfertFicheSanitaire: 1,
} as const;
export type Service = (typeof Service)[keyof typeof Service];

export const ServiceLabels: Record<Service, string> = {
  [Service.TransfertFicheSanitaire]: "",
};
