package dossiers

import (
	"math/rand"
	"registro/sql/personnes"
	"registro/sql/shared"
	"time"
)

// Code generated by gomacro/generator/go/randdata. DO NOT EDIT.

func randCurrency() Currency {
	choix := [...]Currency{Euros, FrancsSuisse}
	i := rand.Intn(len(choix))
	return choix[i]
}

func randDossier() Dossier {
	var s Dossier
	s.Id = randIdDossier()
	s.IdTaux = randIdTaux()
	s.IdResponsable = randper_IdPersonne()
	s.CopiesMails = randper_Mails()
	s.PartageAdressesOK = randbool()
	s.IsValidated = randbool()
	s.LastConnection = randtTime()
	s.KeyV1 = randstring()

	return s
}

func randIdDossier() IdDossier {
	return IdDossier(randint64())
}

func randIdPaiement() IdPaiement {
	return IdPaiement(randint64())
}

func randIdTaux() IdTaux {
	return IdTaux(randint64())
}

func randModePaiement() ModePaiement {
	choix := [...]ModePaiement{Cheque, EnLigne, Virement, Especes, Ancv, Helloasso}
	i := rand.Intn(len(choix))
	return choix[i]
}

func randMontant() Montant {
	var s Montant
	s.Cent = randint()
	s.Currency = randCurrency()

	return s
}

func randPaiement() Paiement {
	var s Paiement
	s.Id = randIdPaiement()
	s.IdDossier = randIdDossier()
	s.IsAcompte = randbool()
	s.IsRemboursement = randbool()
	s.Montant = randMontant()
	s.Payeur = randstring()
	s.Mode = randModePaiement()
	s.Date = randsha_Date()
	s.Label = randstring()
	s.Details = randstring()

	return s
}

func randSlicestring() []string {
	l := 3 + rand.Intn(5)
	out := make([]string, l)
	for i := range out {
		out[i] = randstring()
	}
	return out
}

func randTaux() Taux {
	var s Taux
	s.Id = randIdTaux()
	s.Label = randstring()
	s.Euros = randint()
	s.FrancsSuisse = randint()

	return s
}

func randbool() bool {
	i := rand.Int31n(2)
	return i == 1
}

func randint() int {
	return int(rand.Intn(1000000))
}

func randint64() int64 {
	return int64(rand.Intn(1000000))
}

func randper_IdPersonne() personnes.IdPersonne {
	return personnes.IdPersonne(randint64())
}

func randper_Mails() personnes.Mails {
	return personnes.Mails(randSlicestring())
}

func randsha_Date() shared.Date {
	return shared.Date(randtDate())
}

var letterRunes2 = []rune("azertyuiopqsdfghjklmwxcvbn123456789é@!?&èïab ")

func randstring() string {
	b := make([]rune, 10)
	maxLength := len(letterRunes2)
	for i := range b {
		b[i] = letterRunes2[rand.Intn(maxLength)]
	}
	return string(b)
}

func randtDate() time.Time {
	return time.Unix(int64(rand.Int31()), 5)
}

func randtTime() time.Time {
	return time.Unix(int64(rand.Int31()), 5)
}
