package dossiers

import (
	"math/rand"
	"registro/sql/camps"
	"registro/sql/personnes"
	"registro/sql/shared"
	"time"
)

// Code generated by gomacro/generator/go/randdata. DO NOT EDIT.

func randAide() Aide {
	var s Aide
	s.Id = randIdAide()
	s.IdStructureaide = randIdStructureaide()
	s.IdParticipant = randIdParticipant()
	s.Valide = randbool()
	s.Valeur = randcam_Montant()
	s.ParJour = randbool()
	s.NbJoursMax = randint()

	return s
}

func randBus() Bus {
	choix := [...]Bus{NoBus, Aller, Retour, AllerRetour}
	i := rand.Intn(len(choix))
	return choix[i]
}

func randDossier() Dossier {
	var s Dossier
	s.Id = randIdDossier()
	s.IdPersonne = randper_IdPersonne()
	s.CopiesMails = randper_Mails()
	s.LastConnection = randtTime()
	s.IsValidated = randbool()
	s.PartageAdressesOK = randbool()

	return s
}

func randIdAide() IdAide {
	return IdAide(randint64())
}

func randIdDossier() IdDossier {
	return IdDossier(randint64())
}

func randIdPaiement() IdPaiement {
	return IdPaiement(randint64())
}

func randIdParticipant() IdParticipant {
	return IdParticipant(randint64())
}

func randIdSondage() IdSondage {
	return IdSondage(randint64())
}

func randIdStructureaide() IdStructureaide {
	return IdStructureaide(randint64())
}

func randListeAttente() ListeAttente {
	choix := [...]ListeAttente{ADecider, AttenteProfilInvalide, AttenteCampComplet, EnAttenteReponse, Inscrit}
	i := rand.Intn(len(choix))
	return choix[i]
}

func randModePaiement() ModePaiement {
	choix := [...]ModePaiement{Cheque, EnLigne, Virement, Especes, Ancv, Helloasso}
	i := rand.Intn(len(choix))
	return choix[i]
}

func randPaiement() Paiement {
	var s Paiement
	s.Id = randIdPaiement()
	s.IdDossier = randIdDossier()
	s.IsAcompte = randbool()
	s.IsRemboursement = randbool()
	s.Montant = randcam_Montant()
	s.Payeur = randstring()
	s.Mode = randModePaiement()
	s.Date = randsha_Date()
	s.Label = randstring()
	s.Details = randstring()

	return s
}

func randParticipant() Participant {
	var s Participant
	s.Id = randIdParticipant()
	s.IdCamp = randcam_IdCamp()
	s.IdPersonne = randper_IdPersonne()
	s.IdDossier = randIdDossier()
	s.ListeAttente = randListeAttente()
	s.Remises = randRemises()
	s.QuotientFamilial = randint()
	s.Details = randstring()
	s.Bus = randBus()

	return s
}

func randRemises() Remises {
	var s Remises
	s.ReducEquipiers = randint()
	s.ReducEnfants = randint()
	s.ReducSpeciale = randcam_Montant()

	return s
}

func randSatisfaction() Satisfaction {
	choix := [...]Satisfaction{NoSatisfaction, Decevant, Moyen, Satisfaisant, Tressatisfaisant}
	i := rand.Intn(len(choix))
	return choix[i]
}

func randSlicestring() []string {
	l := 3 + rand.Intn(5)
	out := make([]string, l)
	for i := range out {
		out[i] = randstring()
	}
	return out
}

func randSondage() Sondage {
	var s Sondage
	s.IdSondage = randIdSondage()
	s.IdCamp = randcam_IdCamp()
	s.IdDossier = randIdDossier()
	s.Modified = randtTime()
	s.InfosAvantSejour = randSatisfaction()
	s.InfosPendantSejour = randSatisfaction()
	s.Hebergement = randSatisfaction()
	s.Activites = randSatisfaction()
	s.Theme = randSatisfaction()
	s.Nourriture = randSatisfaction()
	s.Hygiene = randSatisfaction()
	s.Ambiance = randSatisfaction()
	s.Ressenti = randSatisfaction()
	s.MessageEnfant = randstring()
	s.MessageResponsable = randstring()

	return s
}

func randStructureaide() Structureaide {
	var s Structureaide
	s.Id = randint64()
	s.Nom = randstring()
	s.Immatriculation = randstring()
	s.Adresse = randstring()
	s.CodePostal = randstring()
	s.Ville = randstring()
	s.Telephone = randper_Tel()
	s.Info = randstring()

	return s
}

func randbool() bool {
	i := rand.Int31n(2)
	return i == 1
}

func randcam_Currency() camps.Currency {
	choix := [...]camps.Currency{camps.Empty, camps.Euros, camps.FrancsSuisse}
	i := rand.Intn(len(choix))
	return choix[i]
}

func randcam_IdCamp() camps.IdCamp {
	return camps.IdCamp(randint64())
}

func randcam_Montant() camps.Montant {
	var s camps.Montant
	s.Cent = randint()
	s.Currency = randcam_Currency()

	return s
}

func randint() int {
	return int(rand.Intn(1000000))
}

func randint64() int64 {
	return int64(rand.Intn(1000000))
}

func randper_IdPersonne() personnes.IdPersonne {
	return personnes.IdPersonne(randint64())
}

func randper_Mails() personnes.Mails {
	return personnes.Mails(randSlicestring())
}

func randper_Tel() personnes.Tel {
	return personnes.Tel(randstring())
}

func randsha_Date() shared.Date {
	return shared.Date(randtDate())
}

var letterRunes2 = []rune("azertyuiopqsdfghjklmwxcvbn123456789é@!?&èïab ")

func randstring() string {
	b := make([]rune, 10)
	maxLength := len(letterRunes2)
	for i := range b {
		b[i] = letterRunes2[rand.Intn(maxLength)]
	}
	return string(b)
}

func randtDate() time.Time {
	return time.Unix(int64(rand.Int31()), 5)
}

func randtTime() time.Time {
	return time.Unix(int64(rand.Int31()), 5)
}
