package personnes

import (
	"math/rand"
	"registro/sql/shared"
	"time"
)

// Code generated by gomacro/generator/go/randdata. DO NOT EDIT.

func randAllergies() Allergies {
	var s Allergies
	s.Asthme = randbool()
	s.Alimentaires = randbool()
	s.Medicamenteuses = randbool()
	s.Autres = randstring()
	s.ConduiteATenir = randstring()

	return s
}

func randApprofondissement() Approfondissement {
	choix := [...]Approfondissement{AAucun, AAutre, ASb, ACanoe, AVoile, AMoto}
	i := rand.Intn(len(choix))
	return choix[i]
}

func randDepartement() Departement {
	return Departement(randstring())
}

func randDiplome() Diplome {
	choix := [...]Diplome{DAucun, DBafa, DBafaStag, DBafd, DBafdStag, DCap, DAssSociale, DEducSpe, DMonEduc, DInstit, DProf, DAgreg, DBjeps, DDut, DEje, DDeug, DStaps, DBapaat, DBeatep, DZzautre}
	i := rand.Intn(len(choix))
	return choix[i]
}

func randFichesanitaire() Fichesanitaire {
	var s Fichesanitaire
	s.IdPersonne = randIdPersonne()
	s.TraitementMedical = randbool()
	s.Maladies = randMaladies()
	s.Allergies = randAllergies()
	s.DifficultesSante = randstring()
	s.Recommandations = randstring()
	s.Handicap = randbool()
	s.Tel = randTel()
	s.Medecin = randMedecin()
	s.LastModif = randtTime()
	s.Mails = randMails()

	return s
}

func randIdPersonne() IdPersonne {
	return IdPersonne(randint64())
}

func randMails() Mails {
	return Mails(randSlicestring())
}

func randMaladies() Maladies {
	var s Maladies
	s.Rubeole = randbool()
	s.Varicelle = randbool()
	s.Angine = randbool()
	s.Oreillons = randbool()
	s.Scarlatine = randbool()
	s.Coqueluche = randbool()
	s.Otite = randbool()
	s.Rougeole = randbool()
	s.Rhumatisme = randbool()

	return s
}

func randMedecin() Medecin {
	var s Medecin
	s.Nom = randstring()
	s.Tel = randTel()

	return s
}

func randNationnalite() Nationnalite {
	choix := [...]Nationnalite{Autre, Francaise, Suisse}
	i := rand.Intn(len(choix))
	return choix[i]
}

func randPays() Pays {
	return Pays(randstring())
}

func randPersonne() Personne {
	var s Personne
	s.Id = randIdPersonne()
	s.Nom = randstring()
	s.Prenom = randstring()
	s.Sexe = randSexe()
	s.DateNaissance = randsha_Date()
	s.VilleNaissance = randstring()
	s.DepartementNaissance = randDepartement()
	s.Nationnalite = randNationnalite()
	s.Tels = randTels()
	s.Mail = randstring()
	s.Adresse = randstring()
	s.CodePostal = randstring()
	s.Ville = randstring()
	s.Pays = randPays()
	s.SecuriteSociale = randstring()
	s.NomJeuneFille = randstring()
	s.Profession = randstring()
	s.Etudiant = randbool()
	s.Fonctionnaire = randbool()
	s.Diplome = randDiplome()
	s.Approfondissement = randApprofondissement()
	s.Publicite = randPublicite()
	s.IsTemp = randbool()

	return s
}

func randPublicite() Publicite {
	var s Publicite
	s.VersionPapier = randbool()
	s.PubHiver = randbool()
	s.PubEte = randbool()
	s.EchoRocher = randbool()
	s.Eonews = randbool()

	return s
}

func randSexe() Sexe {
	choix := [...]Sexe{Empty, Woman, Man}
	i := rand.Intn(len(choix))
	return choix[i]
}

func randSlicestring() []string {
	l := 3 + rand.Intn(5)
	out := make([]string, l)
	for i := range out {
		out[i] = randstring()
	}
	return out
}

func randTel() Tel {
	return Tel(randstring())
}

func randTels() Tels {
	return Tels(randSlicestring())
}

func randbool() bool {
	i := rand.Int31n(2)
	return i == 1
}

func randint64() int64 {
	return int64(rand.Intn(1000000))
}

func randsha_Date() shared.Date {
	return shared.Date(randtDate())
}

var letterRunes2 = []rune("azertyuiopqsdfghjklmwxcvbn123456789é@!?&èïab ")

func randstring() string {
	b := make([]rune, 10)
	maxLength := len(letterRunes2)
	for i := range b {
		b[i] = letterRunes2[rand.Intn(maxLength)]
	}
	return string(b)
}

func randtDate() time.Time {
	return time.Unix(int64(rand.Int31()), 5)
}

func randtTime() time.Time {
	return time.Unix(int64(rand.Int31()), 5)
}
