/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CampHeaderRow: typeof import('./src/components/app/camps/CampHeaderRow.vue')['default']
    CampStats: typeof import('./src/components/app/camps/CampStats.vue')['default']
    NavBar: typeof import('./src/components/app/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
