/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApprofondissementField: typeof import('./src/components/ApprofondissementField.vue')['default']
    BoolField: typeof import('./src/components/BoolField.vue')['default']
    CardSimilaires: typeof import('./src/components/inscriptions/CardSimilaires.vue')['default']
    CardValide: typeof import('./src/components/inscriptions/CardValide.vue')['default']
    DateField: typeof import('./src/components/DateField.vue')['default']
    DateNaissanceField: typeof import('./src/components/DateNaissanceField.vue')['default']
    DayOffsetField: typeof import('./src/components/DayOffsetField.vue')['default']
    DebounceField: typeof import('./src/components/DebounceField.vue')['default']
    DiplomeField: typeof import('./src/components/DiplomeField.vue')['default']
    EventAccuseReceptionV: typeof import('./src/components/events/EventAccuseReceptionV.vue')['default']
    EventAttestationV: typeof import('./src/components/events/EventAttestationV.vue')['default']
    EventCampDocsV: typeof import('./src/components/events/EventCampDocsV.vue')['default']
    EventFactureV: typeof import('./src/components/events/EventFactureV.vue')['default']
    EventInscriptionTimeV: typeof import('./src/components/events/EventInscriptionTimeV.vue')['default']
    EventItem: typeof import('./src/components/events/EventItem.vue')['default']
    EventMessageV: typeof import('./src/components/events/EventMessageV.vue')['default']
    EventPaiementV: typeof import('./src/components/events/EventPaiementV.vue')['default']
    EventPlaceLibereeV: typeof import('./src/components/events/EventPlaceLibereeV.vue')['default']
    EventSondageV: typeof import('./src/components/events/EventSondageV.vue')['default']
    EventSupprimeV: typeof import('./src/components/events/EventSupprimeV.vue')['default']
    EventSwitch: typeof import('./src/components/EventSwitch.vue')['default']
    FileCard: typeof import('./src/components/files/FileCard.vue')['default']
    FilesDemande: typeof import('./src/components/files/FilesDemande.vue')['default']
    FileUpload: typeof import('./src/components/files/FileUpload.vue')['default']
    InscriptionEtatcivilCols: typeof import('./src/components/inscriptions/InscriptionEtatcivilCols.vue')['default']
    InscriptionRow: typeof import('./src/components/inscriptions/InscriptionRow.vue')['default']
    IntField: typeof import('./src/components/IntField.vue')['default']
    ListeAttenteField: typeof import('./src/components/ListeAttenteField.vue')['default']
    ModePaiementField: typeof import('./src/components/ModePaiementField.vue')['default']
    MontantField: typeof import('./src/components/MontantField.vue')['default']
    NationaliteField: typeof import('./src/components/NationaliteField.vue')['default']
    NavetteField: typeof import('./src/components/NavetteField.vue')['default']
    ParticipantEdit: typeof import('./src/components/inscriptions/ParticipantEdit.vue')['default']
    ParticipantRow: typeof import('./src/components/inscriptions/ParticipantRow.vue')['default']
    ParticipantRowHeader: typeof import('./src/components/inscriptions/ParticipantRowHeader.vue')['default']
    PaysField: typeof import('./src/components/PaysField.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectCamp: typeof import('./src/components/SelectCamp.vue')['default']
    SelectDossier: typeof import('./src/components/SelectDossier.vue')['default']
    SelectPersonne: typeof import('./src/components/SelectPersonne.vue')['default']
    SexeField: typeof import('./src/components/SexeField.vue')['default']
    StringList: typeof import('./src/components/StringList.vue')['default']
    TimeField: typeof import('./src/components/TimeField.vue')['default']
  }
}
