/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CampEdit: typeof import('./src/components/backoffice/camps/CampEdit.vue')['default']
    CampHeaderRow: typeof import('./src/components/backoffice/camps/CampHeaderRow.vue')['default']
    CampStats: typeof import('./src/components/backoffice/camps/CampStats.vue')['default']
    DateField: typeof import('./src/components/shared/DateField.vue')['default']
    IntField: typeof import('./src/components/shared/IntField.vue')['default']
    MontantField: typeof import('./src/components/shared/MontantField.vue')['default']
    NavBar: typeof import('./src/components/backoffice/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TauxSelect: typeof import('./src/components/backoffice/camps/TauxSelect.vue')['default']
  }
}
