// Code generated by gomacro/typescript/axios_api.go. DO NOT EDIT

import type { AxiosResponse } from "axios";
import Axios from "axios";

export type Ar4_Int = [Int, Int, Int, Int];

// AAAA-MM-YY date format
export type Date_ = string & { __opaque__: "Date" };

export type Int = number & { __opaque__: "Int" };
// registro/controllers/central.CampHeader
export interface CampHeader {
  Camp: CampExt;
  Taux: Taux;
  Stats: StatistiquesInscrits;
}
// registro/controllers/central.CampsCreateManyIn
export interface CampsCreateManyIn {
  Taux: Taux;
  Count: Int;
}
// registro/controllers/central.CampsSetTauxIn
export interface CampsSetTauxIn {
  IdCamp: IdCamp;
  Taux: Taux;
}
// registro/sql/camps.Camp
export interface Camp {
  Id: IdCamp;
  IdTaux: IdTaux;
  Nom: string;
  DateDebut: Date;
  Duree: Int;
  Lieu: string;
  Agrement: string;
  Description: string;
  Navette: Navette;
  Places: Int;
  AgeMin: Int;
  AgeMax: Int;
  Ouvert: boolean;
  Prix: Montant;
  OptionPrix: OptionPrixCamp;
  OptionQuotientFamilial: OptionQuotientFamilial;
  Password: string;
}
// registro/sql/camps.CampExt
export interface CampExt {
  Camp: Camp;
  IsTerminated: boolean;
}
// registro/sql/camps.IdCamp
export type IdCamp = Int;
// registro/sql/camps.Navette
export interface Navette {
  Actif: boolean;
  Commentaire: string;
}
// registro/sql/camps.OptionPrixCamp
export interface OptionPrixCamp {
  Active: OptionPrixKind;
  Semaine: OptionSemaineCamp;
  Statuts: PrixParStatut[] | null;
  Jour: Montant[] | null;
}
// registro/sql/camps.OptionPrixKind
export const OptionPrixKind = {
  NoOption: 0,
  PrixSemaine: 1,
  PrixStatut: 2,
  PrixJour: 3,
} as const;
export type OptionPrixKind =
  (typeof OptionPrixKind)[keyof typeof OptionPrixKind];

export const OptionPrixKindLabels: { [key in OptionPrixKind]: string } = {
  [OptionPrixKind.NoOption]: "",
  [OptionPrixKind.PrixSemaine]: "",
  [OptionPrixKind.PrixStatut]: "",
  [OptionPrixKind.PrixJour]: "",
};

// registro/sql/camps.OptionQuotientFamilial
export type OptionQuotientFamilial = Ar4_Int;
// registro/sql/camps.OptionSemaineCamp
export interface OptionSemaineCamp {
  Plage1: Plage;
  Plage2: Plage;
  Prix1: Montant;
  Prix2: Montant;
}
// registro/sql/camps.PrixParStatut
export interface PrixParStatut {
  Id: Int;
  Prix: Montant;
  Statut: string;
  Description: string;
}
// registro/sql/camps.StatistiquesInscrits
export interface StatistiquesInscrits {
  Inscriptions: Int;
  InscriptionsFilles: Int;
  InscriptionsSuisses: Int;
  Valides: Int;
  ValidesFilles: Int;
  ValidesSuisses: Int;
  Refus: Int;
  AStatuer: Int;
  Exceptions: Int;
  Attente: Int;
}
// registro/sql/dossiers.Currency
export const Currency = {
  Euros: 0,
  FrancsSuisse: 1,
} as const;
export type Currency = (typeof Currency)[keyof typeof Currency];

export const CurrencyLabels: { [key in Currency]: string } = {
  [Currency.Euros]: "€",
  [Currency.FrancsSuisse]: "CHF",
};

// registro/sql/dossiers.IdTaux
export type IdTaux = Int;
// registro/sql/dossiers.Montant
export interface Montant {
  Cent: Int;
  Currency: Currency;
}
// registro/sql/dossiers.Taux
export interface Taux {
  Id: IdTaux;
  Label: string;
  Euros: Int;
  FrancsSuisse: Int;
}
// registro/sql/dossiers.Tauxs
export type Tauxs = { [key in IdTaux]: Taux } | null;
// registro/sql/shared.Date
export type Date = Date_;
// registro/sql/shared.Plage
export interface Plage {
  From: Date;
  Duree: Int;
}

/** AbstractAPI provides auto-generated API calls and should be used 
		as base class for an app controller.
	*/
export abstract class AbstractAPI {
  constructor(
    protected baseUrl: string,
    protected authToken: string,
  ) {}

  protected abstract handleError(error: any): void;

  protected abstract startRequest(): void;

  getHeaders() {
    return { Authorization: "Bearer " + this.authToken };
  }

  protected async rawCampsGet() {
    const fullUrl = this.baseUrl + "/api/v1/app/camps";
    const rep: AxiosResponse<CampHeader[] | null> = await Axios.get(fullUrl, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** CampsGet wraps rawCampsGet and handles the error */
  async CampsGet() {
    this.startRequest();
    try {
      const out = await this.rawCampsGet();
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected async rawCampsCreate() {
    const fullUrl = this.baseUrl + "/api/v1/app/camps";
    const rep: AxiosResponse<CampHeader> = await Axios.put(fullUrl, null, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** CampsCreate wraps rawCampsCreate and handles the error */
  async CampsCreate() {
    this.startRequest();
    try {
      const out = await this.rawCampsCreate();
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected async rawCampsCreateMany(params: CampsCreateManyIn) {
    const fullUrl = this.baseUrl + "/api/v1/app/camps-many";
    const rep: AxiosResponse<CampHeader[] | null> = await Axios.put(
      fullUrl,
      params,
      { headers: this.getHeaders() },
    );
    return rep.data;
  }

  /** CampsCreateMany wraps rawCampsCreateMany and handles the error */
  async CampsCreateMany(params: CampsCreateManyIn) {
    this.startRequest();
    try {
      const out = await this.rawCampsCreateMany(params);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected async rawCampsUpdate(params: Camp) {
    const fullUrl = this.baseUrl + "/api/v1/app/camps";
    const rep: AxiosResponse<CampExt> = await Axios.post(fullUrl, params, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** CampsUpdate wraps rawCampsUpdate and handles the error */
  async CampsUpdate(params: Camp) {
    this.startRequest();
    try {
      const out = await this.rawCampsUpdate(params);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected async rawCampsDelete(params: { id: Int }) {
    const fullUrl = this.baseUrl + "/api/v1/app/camps";
    await Axios.delete(fullUrl, {
      headers: this.getHeaders(),
      params: { id: String(params["id"]) },
    });
    return true;
  }

  /** CampsDelete wraps rawCampsDelete and handles the error */
  async CampsDelete(params: { id: Int }) {
    this.startRequest();
    try {
      const out = await this.rawCampsDelete(params);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected async rawCampsGetTaux() {
    const fullUrl = this.baseUrl + "/api/v1/app/camps-taux";
    const rep: AxiosResponse<Tauxs> = await Axios.get(fullUrl, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** CampsGetTaux wraps rawCampsGetTaux and handles the error */
  async CampsGetTaux() {
    this.startRequest();
    try {
      const out = await this.rawCampsGetTaux();
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected async rawCampsSetTaux(params: CampsSetTauxIn) {
    const fullUrl = this.baseUrl + "/api/v1/app/camps-taux";
    const rep: AxiosResponse<CampHeader> = await Axios.post(fullUrl, params, {
      headers: this.getHeaders(),
    });
    return rep.data;
  }

  /** CampsSetTaux wraps rawCampsSetTaux and handles the error */
  async CampsSetTaux(params: CampsSetTauxIn) {
    this.startRequest();
    try {
      const out = await this.rawCampsSetTaux(params);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }
}
