// Code generated by gomacro/typescript/axios_api.go. DO NOT EDIT

import type { AxiosResponse } from "axios";
import Axios from "axios";

export type Ar2_string = [string, string];

// AAAA-MM-YY date format
export type Date_ = string & { __opaque__: "Date" };

export type Int = number & { __opaque__: "Int" };

// ISO date-time string
export type Time = string & { __opaque__: "Time" };

// database/sql.NullBool
export interface NullBool {
  Bool: boolean;
  Valid: boolean;
}
// registro/controllers/equipier.Camp
export interface Camp {
  Nom: string;
  DateDebut: Date;
  Duree: Int;
}
// registro/controllers/equipier.DemandeEquipier
export interface DemandeEquipier {
  Demande: Demande;
  Optionnelle: boolean;
  Files: PublicFile[] | null;
}
// registro/controllers/equipier.EquipierExt
export interface EquipierExt {
  Equipier: Equipier;
  PersonneBase: Identite;
  PersonneDetails: Ficheequipier;
  Camp: Camp;
  Demandes: DemandeEquipier[] | null;
}
// registro/controllers/equipier.Photos
export interface Photos {
  HasAlbum: boolean;
  URL: string;
}
// registro/controllers/equipier.UpdateIn
export interface UpdateIn {
  Token: string;
  PersonneBase: Identite;
  PersonneDetails: Ficheequipier;
  Presence: PresenceOffsets;
}
// registro/logic.PublicFile
export interface PublicFile {
  Key: string;
  Id: IdFile;
  Taille: Int;
  NomClient: string;
  Uploaded: Time;
}
// registro/sql/camps.Equipier
export interface Equipier {
  Id: IdEquipier;
  IdCamp: IdCamp;
  IdPersonne: IdPersonne;
  Roles: Roles;
  Presence: PresenceOffsets;
  FormStatus: FormStatusEquipier;
  AccepteCharte: NullBool;
}
// registro/sql/camps.FormStatusEquipier
export const FormStatusEquipier = {
  NotSend: 0,
  Pending: 1,
  Answered: 2,
} as const;
export type FormStatusEquipier =
  (typeof FormStatusEquipier)[keyof typeof FormStatusEquipier];

export const FormStatusEquipierLabels: Record<FormStatusEquipier, string> = {
  [FormStatusEquipier.NotSend]: "Non envoyé",
  [FormStatusEquipier.Pending]: "En attente de réponse",
  [FormStatusEquipier.Answered]: "Répondu",
};

export type IdCamp = Int & { __opaque_int__: "IdCamp" };
export type IdEquipier = Int & { __opaque_int__: "IdEquipier" };
// registro/sql/camps.PresenceOffsets
export interface PresenceOffsets {
  Debut: Int;
  Fin: Int;
}
// registro/sql/camps.Role
export const Role = {
  Direction: 0,
  Adjoint: 1,
  Animation: 2,
  Menage: 3,
  Cuisine: 4,
  Intendance: 5,
  Infirmerie: 6,
  AideAnimation: 7,
  Lingerie: 8,
  Chauffeur: 9,
  Factotum: 10,
  Babysiter: 11,
  AutreRole: 12,
} as const;
export type Role = (typeof Role)[keyof typeof Role];

export const RoleLabels: Record<Role, string> = {
  [Role.Direction]: "Direction",
  [Role.Adjoint]: "Adjoint",
  [Role.Animation]: "Animation",
  [Role.Menage]: "Ménage",
  [Role.Cuisine]: "Cuisine",
  [Role.Intendance]: "Intendance",
  [Role.Infirmerie]: "Assistant sanitaire",
  [Role.AideAnimation]: "Aide-animateur",
  [Role.Lingerie]: "Lingerie",
  [Role.Chauffeur]: "Chauffeur",
  [Role.Factotum]: "Factotum",
  [Role.Babysiter]: "Baby-sitter",
  [Role.AutreRole]: "Autre",
};

// registro/sql/camps.Roles
export type Roles = Role[] | null;
// registro/sql/files.Categorie
export const Categorie = {
  NoBuiltin: 0,
  CarteId: 1,
  Permis: 2,
  SB: 3,
  Secourisme: 4,
  Bafa: 5,
  Bafd: 6,
  CarteVitale: 7,
  Vaccins: 8,
  Haccp: 9,
  BafdEquiv: 10,
  BafaEquiv: 11,
  CertMedicalCuisine: 12,
  PhotoIdentite: 13,
  ExtraitCasierJudiciaire: 14,
  Autre: 15,
} as const;
export type Categorie = (typeof Categorie)[keyof typeof Categorie];

export const CategorieLabels: Record<Categorie, string> = {
  [Categorie.NoBuiltin]: "-",
  [Categorie.CarteId]: "Carte d'identité/Passeport",
  [Categorie.Permis]: "Permis de conduire",
  [Categorie.SB]: "Surveillant de baignade",
  [Categorie.Secourisme]: "Secourisme (PSC1 - AFPS)",
  [Categorie.Bafa]: "BAFA",
  [Categorie.Bafd]: "BAFD",
  [Categorie.CarteVitale]: "Carte Vitale",
  [Categorie.Vaccins]: "Vaccins",
  [Categorie.Haccp]: "Cuisine (HACCP)",
  [Categorie.BafdEquiv]: "Equivalent BAFD",
  [Categorie.BafaEquiv]: "Equivalent BAFA",
  [Categorie.CertMedicalCuisine]: "Certificat médical cuisine",
  [Categorie.PhotoIdentite]: "Photo d'identité",
  [Categorie.ExtraitCasierJudiciaire]: "Extrait du casier judiciaire",
  [Categorie.Autre]: "Autre",
};

// registro/sql/files.Demande
export interface Demande {
  Id: IdDemande;
  IdFile: OptID_IdFile;
  IdDirecteur: OptID_IdPersonne;
  Categorie: Categorie;
  Description: string;
  MaxDocs: Int;
  JoursValide: Int;
}
export type IdDemande = Int & { __opaque_int__: "IdDemande" };
export type IdFile = Int & { __opaque_int__: "IdFile" };
// registro/sql/personnes.Approfondissement
export const Approfondissement = {
  AAucun: 0,
  AAutre: 1,
  ASb: 2,
  ACanoe: 3,
  AVoile: 4,
  AMoto: 5,
} as const;
export type Approfondissement =
  (typeof Approfondissement)[keyof typeof Approfondissement];

export const ApprofondissementLabels: Record<Approfondissement, string> = {
  [Approfondissement.AAucun]: "Non effectué",
  [Approfondissement.AAutre]: "Approfondissement",
  [Approfondissement.ASb]: "Surveillant de baignade",
  [Approfondissement.ACanoe]: "Canoë - Kayak",
  [Approfondissement.AVoile]: "Voile",
  [Approfondissement.AMoto]: "Loisirs motocyclistes",
};

// registro/sql/personnes.Diplome
export const Diplome = {
  DAucun: 0,
  DAcveBafa: 1,
  DAcveBafaStag: 2,
  DAcveBafd: 3,
  DAcveBafdStag: 4,
  DAcveCap: 5,
  DAcveAssSociale: 6,
  DAcveEducSpe: 7,
  DAcveMonEduc: 8,
  DAcveInstit: 9,
  DAcveProf: 10,
  DAcveAgreg: 11,
  DAcveBjeps: 12,
  DAcveDut: 13,
  DAcveEje: 14,
  DAcveDeug: 15,
  DAcveStaps: 16,
  DAcveBapaat: 17,
  DAcveBeatep: 18,
  DRepereJsMoniteur: 19,
  DRepereJsDirecteur: 20,
  DRepereBafa: 21,
  DRepereBafd: 22,
  DRepereForje: 23,
  DAutre: 24,
} as const;
export type Diplome = (typeof Diplome)[keyof typeof Diplome];

export const DiplomeLabels: Record<Diplome, string> = {
  [Diplome.DAucun]: "Aucun",
  [Diplome.DAcveBafa]: "BAFA Titulaire",
  [Diplome.DAcveBafaStag]: "BAFA Stagiaire",
  [Diplome.DAcveBafd]: "BAFD titulaire",
  [Diplome.DAcveBafdStag]: "BAFD stagiaire",
  [Diplome.DAcveCap]: "CAP petit enfance",
  [Diplome.DAcveAssSociale]: "Assitante Sociale",
  [Diplome.DAcveEducSpe]: "Educ. spé.",
  [Diplome.DAcveMonEduc]: "Moniteur educateur",
  [Diplome.DAcveInstit]: "Professeur des écoles",
  [Diplome.DAcveProf]: "Enseignant du secondaire",
  [Diplome.DAcveAgreg]: "Agrégé",
  [Diplome.DAcveBjeps]: "BPJEPS",
  [Diplome.DAcveDut]: "DUT carrière sociale",
  [Diplome.DAcveEje]: "EJE",
  [Diplome.DAcveDeug]: "DEUG",
  [Diplome.DAcveStaps]: "STAPS",
  [Diplome.DAcveBapaat]: "BAPAAT",
  [Diplome.DAcveBeatep]: "BEATEP",
  [Diplome.DRepereJsMoniteur]: "Formation JS Moniteur",
  [Diplome.DRepereJsDirecteur]: "Formation JS Directeur",
  [Diplome.DRepereBafa]: "BAFA",
  [Diplome.DRepereBafd]: "BAFD",
  [Diplome.DRepereForje]: "Formation Forje (GLAJ)",
  [Diplome.DAutre]: "Autre (à préciser)",
};

// registro/sql/personnes.EtatCivil
export const EtatCivil = {
  NoEtatCivil: 0,
  Marie: 1,
  Celibataire: 2,
} as const;
export type EtatCivil = (typeof EtatCivil)[keyof typeof EtatCivil];

export const EtatCivilLabels: Record<EtatCivil, string> = {
  [EtatCivil.NoEtatCivil]: "",
  [EtatCivil.Marie]: "Marié(e)",
  [EtatCivil.Celibataire]: "Célibataire",
};

// registro/sql/personnes.Ficheequipier
export interface Ficheequipier {
  IdPersonne: IdPersonne;
  SecuriteSociale: string;
  Diplome: Diplome;
  Formation: string;
  Fonctionnaire: boolean;
  Approfondissement: Approfondissement;
  EtatCivil: EtatCivil;
  NombreEnfants: Int;
  Profession: string;
  ExperienceTravailJeunes: string;
  ParcoursSpirituel: string;
  Eglise: string;
  Recommandation: Recommandation;
  Sante: string;
  AssuranceMaladie: string;
  AssuranceAccident: string;
  DemandeMembreAssoPermanent: boolean;
  FormationRepere: FormationRepere;
}
// registro/sql/personnes.FormationRepere
export const FormationRepere = {
  FRAucun: 0,
  FRCfcAssistantESocioEducatif: 1,
  FRMaitreSocioProfessionnel: 2,
  FREnseignementScolaire: 3,
  FRTravailSocial: 4,
} as const;
export type FormationRepere =
  (typeof FormationRepere)[keyof typeof FormationRepere];

export const FormationRepereLabels: Record<FormationRepere, string> = {
  [FormationRepere.FRAucun]: "",
  [FormationRepere.FRCfcAssistantESocioEducatif]:
    "CFC assistant(e) socio-éducatif",
  [FormationRepere.FRMaitreSocioProfessionnel]: "Maitre socio-professionnel",
  [FormationRepere.FREnseignementScolaire]: "Enseignement scolaire",
  [FormationRepere.FRTravailSocial]: "Travail social",
};

export type IdPersonne = Int & { __opaque_int__: "IdPersonne" };
// registro/sql/personnes.Identite
export interface Identite {
  Nom: string;
  Prenom: string;
  Sexe: Sexe;
  DateNaissance: Date;
  Nationnalite: Nationnalite;
  Tels: Tels;
  Mail: string;
  Adresse: string;
  CodePostal: string;
  Ville: string;
  Pays: Pays;
}
// registro/sql/personnes.Nationnalite
export interface Nationnalite {
  IsSuisse: boolean;
}
// registro/sql/personnes.Pays
export type Pays = string;
// registro/sql/personnes.Recommandation
export interface Recommandation {
  Nom: string;
  Prenom: string;
  Mail: string;
  Tel: Tel;
}
// registro/sql/personnes.Sexe
export const Sexe = {
  NoSexe: 0,
  Woman: 1,
  Man: 2,
} as const;
export type Sexe = (typeof Sexe)[keyof typeof Sexe];

export const SexeLabels: Record<Sexe, string> = {
  [Sexe.NoSexe]: "",
  [Sexe.Woman]: "Femme",
  [Sexe.Man]: "Homme",
};

// registro/sql/personnes.Tel
export type Tel = string;
// registro/sql/personnes.Tels
export type Tels = Ar2_string;
// registro/sql/shared.Date
export type Date = Date_;
// registro/sql/shared.OptID[registro/sql/files.IdFile]
export interface OptID_IdFile {
  Id: IdFile;
  Valid: boolean;
}
// registro/sql/shared.OptID[registro/sql/personnes.IdPersonne]
export interface OptID_IdPersonne {
  Id: IdPersonne;
  Valid: boolean;
}

/** AbstractAPI provides auto-generated API calls and should be used 
		as base class for an app controller.
	*/
export abstract class AbstractAPI {
  constructor(
    protected baseURL: string,
    public authToken: string,
  ) {}

  protected abstract handleError(error: any): void;

  protected abstract startRequest(): void;

  getHeaders() {
    return { Authorization: "Bearer " + this.authToken };
  }

  /** Load performs the request and handles the error */
  async Load(params: { token: string }) {
    const fullUrl = this.baseURL + "/api/v1/equipier";
    this.startRequest();
    try {
      const rep: AxiosResponse<EquipierExt> = await Axios.get(fullUrl, {
        headers: this.getHeaders(),
        params: { token: params["token"] },
      });
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** LoadPhotos performs the request and handles the error */
  async LoadPhotos(params: { token: string }) {
    const fullUrl = this.baseURL + "/api/v1/equipier/photos";
    this.startRequest();
    try {
      const rep: AxiosResponse<Photos> = await Axios.get(fullUrl, {
        headers: this.getHeaders(),
        params: { token: params["token"] },
      });
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** Update performs the request and handles the error */
  async Update(params: UpdateIn) {
    const fullUrl = this.baseURL + "/api/v1/equipier";
    this.startRequest();
    try {
      await Axios.post(fullUrl, params, { headers: this.getHeaders() });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** UpdateCharte performs the request and handles the error */
  async UpdateCharte(params: { token: string; accept: boolean }) {
    const fullUrl = this.baseURL + "/api/v1/equipier/charte";
    this.startRequest();
    try {
      await Axios.post(fullUrl, null, {
        headers: this.getHeaders(),
        params: {
          token: params["token"],
          accept: params["accept"] ? "ok" : "",
        },
      });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** UploadDocument performs the request and handles the error */
  async UploadDocument(
    file: File,
    params: { token: string; idDemande: IdDemande },
  ) {
    const fullUrl = this.baseURL + "/api/v1/equipier/upload";
    this.startRequest();
    try {
      const formData = new FormData();
      formData.append("document", file, file.name);
      const rep: AxiosResponse<PublicFile> = await Axios.put(
        fullUrl,
        formData,
        {
          headers: this.getHeaders(),
          params: {
            token: params["token"],
            idDemande: String(params["idDemande"]),
          },
        },
      );
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** DeleteDocument performs the request and handles the error */
  async DeleteDocument(params: { key: string }) {
    const fullUrl = this.baseURL + "/api/v1/equipier/upload";
    this.startRequest();
    try {
      await Axios.delete(fullUrl, {
        headers: this.getHeaders(),
        params: { key: params["key"] },
      });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }
}
