// Code generated by gomacro/typescript/axios_api.go. DO NOT EDIT

import type { AxiosResponse } from "axios";
import Axios from "axios";

// AAAA-MM-YY date format
export type Date_ = string & { __opaque__: "Date" };

export type Int = number & { __opaque__: "Int" };

// ISO date-time string
export type Time = string & { __opaque__: "Time" };

// database/sql.NullBool
export interface NullBool {
  Bool: boolean;
  Valid: boolean;
}
// registro/controllers/equipier.Camp
export interface Camp {
  Nom: string;
  DateDebut: Date;
  Duree: Int;
}
// registro/controllers/equipier.DemandeEquipier
export interface DemandeEquipier {
  Demande: Demande;
  Optionnelle: boolean;
  Files: PublicFile[] | null;
}
// registro/controllers/equipier.EquipierExt
export interface EquipierExt {
  Equipier: Equipier;
  Personne: Etatcivil;
  Camp: Camp;
  Demandes: DemandeEquipier[] | null;
}
// registro/controllers/equipier.Joomeo
export interface Joomeo {
  SpaceURL: string;
  Login: string;
  Password: string;
}
// registro/controllers/equipier.UpdateIn
export interface UpdateIn {
  Token: string;
  Personne: Etatcivil;
  Presence: PresenceOffsets;
}
// registro/controllers/files.PublicFile
export interface PublicFile {
  Key: string;
  Id: IdFile;
  Taille: Int;
  NomClient: string;
  Uploaded: Time;
}
// registro/sql/camps.Equipier
export interface Equipier {
  Id: IdEquipier;
  IdCamp: IdCamp;
  IdPersonne: IdPersonne;
  Roles: Roles;
  Presence: PresenceOffsets;
  FormStatus: FormStatusEquipier;
  AccepteCharte: NullBool;
}
// registro/sql/camps.FormStatusEquipier
export const FormStatusEquipier = {
  NotSend: 0,
  Pending: 1,
  Answered: 2,
} as const;
export type FormStatusEquipier =
  (typeof FormStatusEquipier)[keyof typeof FormStatusEquipier];

export const FormStatusEquipierLabels: Record<FormStatusEquipier, string> = {
  [FormStatusEquipier.NotSend]: "Non envoyé",
  [FormStatusEquipier.Pending]: "En attente",
  [FormStatusEquipier.Answered]: "Répondu",
};

export type IdCamp = number & { __opaque__: "IdCamp" };
export type IdEquipier = number & { __opaque__: "IdEquipier" };
// registro/sql/camps.PresenceOffsets
export interface PresenceOffsets {
  Debut: Int;
  Fin: Int;
}
// registro/sql/camps.Role
export const Role = {
  Direction: 0,
  Adjoint: 1,
  Animation: 2,
  Menage: 3,
  Cuisine: 4,
  Intendance: 5,
  Infirmerie: 6,
  AideAnimation: 7,
  Lingerie: 8,
  Chauffeur: 9,
  Factotum: 10,
  Babysiter: 11,
  AutreRole: 12,
} as const;
export type Role = (typeof Role)[keyof typeof Role];

export const RoleLabels: Record<Role, string> = {
  [Role.Direction]: "Direction",
  [Role.Adjoint]: "Adjoint",
  [Role.Animation]: "Animation",
  [Role.Menage]: "Ménage",
  [Role.Cuisine]: "Cuisine",
  [Role.Intendance]: "Intendance",
  [Role.Infirmerie]: "Assistant sanitaire",
  [Role.AideAnimation]: "Aide-animateur",
  [Role.Lingerie]: "Lingerie",
  [Role.Chauffeur]: "Chauffeur",
  [Role.Factotum]: "Factotum",
  [Role.Babysiter]: "Baby-sitter",
  [Role.AutreRole]: "Autre",
};

// registro/sql/camps.Roles
export type Roles = Role[] | null;
// registro/sql/files.Categorie
export const Categorie = {
  NoBuiltin: 0,
  CarteId: 1,
  Permis: 2,
  SB: 3,
  Secourisme: 4,
  Bafa: 5,
  Bafd: 6,
  CarteVitale: 7,
  Vaccins: 8,
  Haccp: 9,
  BafdEquiv: 10,
  BafaEquiv: 11,
  CertMedicalCuisine: 12,
  Scolarite: 13,
  Autre: 14,
  nbCategorieEquipier: 15,
} as const;
export type Categorie = (typeof Categorie)[keyof typeof Categorie];

export const CategorieLabels: Record<Categorie, string> = {
  [Categorie.NoBuiltin]: "-",
  [Categorie.CarteId]: "Carte d'identité/Passeport",
  [Categorie.Permis]: "Permis de conduire",
  [Categorie.SB]: "Surveillant de baignade",
  [Categorie.Secourisme]: "Secourisme (PSC1 - AFPS)",
  [Categorie.Bafa]: "BAFA",
  [Categorie.Bafd]: "BAFD",
  [Categorie.CarteVitale]: "Carte Vitale",
  [Categorie.Vaccins]: "Vaccins",
  [Categorie.Haccp]: "Cuisine (HACCP)",
  [Categorie.BafdEquiv]: "Equivalent BAFD",
  [Categorie.BafaEquiv]: "Equivalent BAFA",
  [Categorie.CertMedicalCuisine]: "Certificat médical cuisine",
  [Categorie.Scolarite]: "Certificat de scolarité",
  [Categorie.Autre]: "Autre",
  [Categorie.nbCategorieEquipier]: "",
};

// registro/sql/files.Demande
export interface Demande {
  Id: IdDemande;
  IdFile: OptID_IdFile;
  IdDirecteur: OptID_IdPersonne;
  Categorie: Categorie;
  Description: string;
  MaxDocs: Int;
  JoursValide: Int;
}
export type IdDemande = number & { __opaque__: "IdDemande" };
export type IdFile = number & { __opaque__: "IdFile" };
// registro/sql/personnes.Approfondissement
export const Approfondissement = {
  AAucun: 0,
  AAutre: 1,
  ASb: 2,
  ACanoe: 3,
  AVoile: 4,
  AMoto: 5,
} as const;
export type Approfondissement =
  (typeof Approfondissement)[keyof typeof Approfondissement];

export const ApprofondissementLabels: Record<Approfondissement, string> = {
  [Approfondissement.AAucun]: "Non effectué",
  [Approfondissement.AAutre]: "Approfondissement",
  [Approfondissement.ASb]: "Surveillant de baignade",
  [Approfondissement.ACanoe]: "Canoë - Kayak",
  [Approfondissement.AVoile]: "Voile",
  [Approfondissement.AMoto]: "Loisirs motocyclistes",
};

// registro/sql/personnes.Departement
export type Departement = string;
// registro/sql/personnes.Diplome
export const Diplome = {
  DAucun: 0,
  DBafa: 1,
  DBafaStag: 2,
  DBafd: 3,
  DBafdStag: 4,
  DCap: 5,
  DAssSociale: 6,
  DEducSpe: 7,
  DMonEduc: 8,
  DInstit: 9,
  DProf: 10,
  DAgreg: 11,
  DBjeps: 12,
  DDut: 13,
  DEje: 14,
  DDeug: 15,
  DStaps: 16,
  DBapaat: 17,
  DBeatep: 18,
  DZzautre: 19,
} as const;
export type Diplome = (typeof Diplome)[keyof typeof Diplome];

export const DiplomeLabels: Record<Diplome, string> = {
  [Diplome.DAucun]: "Aucun",
  [Diplome.DBafa]: "BAFA Titulaire",
  [Diplome.DBafaStag]: "BAFA Stagiaire",
  [Diplome.DBafd]: "BAFD titulaire",
  [Diplome.DBafdStag]: "BAFD stagiaire",
  [Diplome.DCap]: "CAP petit enfance",
  [Diplome.DAssSociale]: "Assitante Sociale",
  [Diplome.DEducSpe]: "Educ. spé.",
  [Diplome.DMonEduc]: "Moniteur educateur",
  [Diplome.DInstit]: "Professeur des écoles",
  [Diplome.DProf]: "Enseignant du secondaire",
  [Diplome.DAgreg]: "Agrégé",
  [Diplome.DBjeps]: "BPJEPS",
  [Diplome.DDut]: "DUT carrière sociale",
  [Diplome.DEje]: "EJE",
  [Diplome.DDeug]: "DEUG",
  [Diplome.DStaps]: "STAPS",
  [Diplome.DBapaat]: "BAPAAT",
  [Diplome.DBeatep]: "BEATEP",
  [Diplome.DZzautre]: "AUTRE",
};

// registro/sql/personnes.Etatcivil
export interface Etatcivil {
  Nom: string;
  Prenom: string;
  Sexe: Sexe;
  DateNaissance: Date;
  VilleNaissance: string;
  DepartementNaissance: Departement;
  Nationnalite: Nationnalite;
  Tels: Tels;
  Mail: string;
  Adresse: string;
  CodePostal: string;
  Ville: string;
  Pays: Pays;
  SecuriteSociale: string;
  NomJeuneFille: string;
  Profession: string;
  Etudiant: boolean;
  Fonctionnaire: boolean;
  Diplome: Diplome;
  Approfondissement: Approfondissement;
}
export type IdPersonne = number & { __opaque__: "IdPersonne" };
// registro/sql/personnes.Nationnalite
export const Nationnalite = {
  Autre: 0,
  Francaise: 1,
  Suisse: 2,
} as const;
export type Nationnalite = (typeof Nationnalite)[keyof typeof Nationnalite];

export const NationnaliteLabels: Record<Nationnalite, string> = {
  [Nationnalite.Autre]: "Autre",
  [Nationnalite.Francaise]: "Française",
  [Nationnalite.Suisse]: "Suisse",
};

// registro/sql/personnes.Pays
export type Pays = string;
// registro/sql/personnes.Sexe
export const Sexe = {
  NoSexe: 0,
  Woman: 1,
  Man: 2,
} as const;
export type Sexe = (typeof Sexe)[keyof typeof Sexe];

export const SexeLabels: Record<Sexe, string> = {
  [Sexe.NoSexe]: "",
  [Sexe.Woman]: "Femme",
  [Sexe.Man]: "Homme",
};

// registro/sql/personnes.Tels
export type Tels = string[] | null;
// registro/sql/shared.Date
export type Date = Date_;
// registro/sql/shared.OptID[registro/sql/files.IdFile]
export interface OptID_IdFile {
  Id: IdFile;
  Valid: boolean;
}
// registro/sql/shared.OptID[registro/sql/personnes.IdPersonne]
export interface OptID_IdPersonne {
  Id: IdPersonne;
  Valid: boolean;
}

/** AbstractAPI provides auto-generated API calls and should be used 
		as base class for an app controller.
	*/
export abstract class AbstractAPI {
  constructor(
    protected baseURL: string,
    protected authToken: string,
  ) {}

  protected abstract handleError(error: any): void;

  protected abstract startRequest(): void;

  getHeaders() {
    return { Authorization: "Bearer " + this.authToken };
  }

  /** Load performs the request and handles the error */
  async Load(params: { token: string }) {
    const fullUrl = this.baseURL + "/api/v1/equipier";
    this.startRequest();
    try {
      const rep: AxiosResponse<EquipierExt> = await Axios.get(fullUrl, {
        headers: this.getHeaders(),
        params: { token: params["token"] },
      });
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** LoadJoomeo performs the request and handles the error */
  async LoadJoomeo(params: { token: string }) {
    const fullUrl = this.baseURL + "/api/v1/equipier/joomeo";
    this.startRequest();
    try {
      const rep: AxiosResponse<Joomeo> = await Axios.get(fullUrl, {
        headers: this.getHeaders(),
        params: { token: params["token"] },
      });
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** Update performs the request and handles the error */
  async Update(params: UpdateIn) {
    const fullUrl = this.baseURL + "/api/v1/equipier";
    this.startRequest();
    try {
      await Axios.post(fullUrl, params, { headers: this.getHeaders() });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** UpdateCharte performs the request and handles the error */
  async UpdateCharte(params: { token: string; accept: boolean }) {
    const fullUrl = this.baseURL + "/api/v1/equipier/charte";
    this.startRequest();
    try {
      await Axios.post(fullUrl, null, {
        headers: this.getHeaders(),
        params: {
          token: params["token"],
          accept: params["accept"] ? "ok" : "",
        },
      });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** UploadDocument performs the request and handles the error */
  async UploadDocument(
    file: File,
    params: { token: string; idDemande: IdDemande },
  ) {
    const fullUrl = this.baseURL + "/api/v1/equipier/upload";
    this.startRequest();
    try {
      const formData = new FormData();
      formData.append("document", file, file.name);
      const rep: AxiosResponse<PublicFile> = await Axios.put(
        fullUrl,
        formData,
        {
          headers: this.getHeaders(),
          params: {
            token: params["token"],
            idDemande: String(params["idDemande"]),
          },
        },
      );
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** DeleteDocument performs the request and handles the error */
  async DeleteDocument(params: { key: string }) {
    const fullUrl = this.baseURL + "/api/v1/equipier/upload";
    this.startRequest();
    try {
      await Axios.delete(fullUrl, {
        headers: this.getHeaders(),
        params: { key: params["key"] },
      });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }
}
