package files

import (
	"math/rand"
	"registro/sql/camps"
	"registro/sql/dossiers"
	"registro/sql/personnes"
	"time"
)

// Code generated by gomacro/generator/go/randdata. DO NOT EDIT.

func randCategorie() Categorie {
	choix := [...]Categorie{Unknown, Bafa, Bafd, CarteId, Permis, Sb, Secour, BafdEquiv, BafaEquiv, CarteVitale, Haccp, CertMedicalCuisine, Scolarite, Autre, Vaccin, TestNautique}
	i := rand.Intn(len(choix))
	return choix[i]
}

func randDemande() Demande {
	var s Demande
	s.Id = randIdDemande()
	s.IdFile = randOptIdFile()
	s.IdDirecteur = randOptIdPersonne()
	s.Categorie = randCategorie()
	s.Description = randstring()
	s.MaxDocs = randint()
	s.JoursValide = randint()

	return s
}

func randDemandeCamp() DemandeCamp {
	var s DemandeCamp
	s.IdCamp = randcam_IdCamp()
	s.IdDemande = randIdDemande()

	return s
}

func randDemandeEquipier() DemandeEquipier {
	var s DemandeEquipier
	s.IdEquipier = randcam_IdEquipier()
	s.IdDemande = randIdDemande()
	s.Optionnel = randbool()

	return s
}

func randFile() File {
	var s File
	s.Id = randIdFile()
	s.Taille = randint()
	s.NomClient = randstring()
	s.DateHeureModif = randtTime()

	return s
}

func randFileAide() FileAide {
	var s FileAide
	s.IdFile = randIdFile()
	s.IdAide = randdos_IdAide()

	return s
}

func randFileCamp() FileCamp {
	var s FileCamp
	s.IdFile = randIdFile()
	s.IdCamp = randcam_IdCamp()
	s.IsLettre = randbool()

	return s
}

func randFilePersonne() FilePersonne {
	var s FilePersonne
	s.IdFile = randIdFile()
	s.IdPersonne = randper_IdPersonne()
	s.IdDemande = randIdDemande()

	return s
}

func randIdDemande() IdDemande {
	return IdDemande(randint64())
}

func randIdFile() IdFile {
	return IdFile(randint64())
}

func randOptIdFile() OptIdFile {
	var s OptIdFile
	s.Id = randIdFile()
	s.Valid = randbool()

	return s
}

func randOptIdPersonne() OptIdPersonne {
	var s OptIdPersonne
	s.Id = randper_IdPersonne()
	s.Valid = randbool()

	return s
}

func randbool() bool {
	i := rand.Int31n(2)
	return i == 1
}

func randcam_IdCamp() camps.IdCamp {
	return camps.IdCamp(randint64())
}

func randcam_IdEquipier() camps.IdEquipier {
	return camps.IdEquipier(randint64())
}

func randdos_IdAide() dossiers.IdAide {
	return dossiers.IdAide(randint64())
}

func randint() int {
	return int(rand.Intn(1000000))
}

func randint64() int64 {
	return int64(rand.Intn(1000000))
}

func randper_IdPersonne() personnes.IdPersonne {
	return personnes.IdPersonne(randint64())
}

var letterRunes2 = []rune("azertyuiopqsdfghjklmwxcvbn123456789é@!?&èïab ")

func randstring() string {
	b := make([]rune, 10)
	maxLength := len(letterRunes2)
	for i := range b {
		b[i] = letterRunes2[rand.Intn(maxLength)]
	}
	return string(b)
}

func randtTime() time.Time {
	return time.Unix(int64(rand.Int31()), 5)
}
