// Code generated by gomacro/typescript/urls_api.go. DO NOT EDIT

export type Int = number & { __opaque__: "Int" };
// registro/controllers/directeurs.LettreImageUploadOut
export interface LettreImageUploadOut {
  location: string;
}
export type IdDemande = number & { __opaque__: "IdDemande" };

/** Endpoints exposes the HTTP urls handled by the server. */
export class Endpoints {
  constructor(private baseURL: string) {}

  EquipiersDownloadFiles(token: string) {
    return (
      this.baseURL + "/api/v1/directeurs/equipiers/files" + `?token=${token}`
    );
  }

  ParticipantsStreamFichesAndVaccins(token: string) {
    return (
      this.baseURL +
      "/api/v1/directeurs/participants/stream-fiches-sanitaires" +
      `?token=${token}`
    );
  }

  DocumentsStreamUploaded(idDemande: IdDemande, token: string) {
    return (
      this.baseURL +
      "/api/v1/directeurs/documents/stream-documents" +
      `?idDemande=${idDemande}&token=${token}`
    );
  }

  LettreImageUpload(token: string) {
    return this.baseURL + "/api/v1/directeurs/lettre-image" + `?token=${token}`;
  }

  RenderDocumentCamp(documentToken: string, isMiniature: boolean) {
    return (
      this.baseURL +
      "/api/v1/document-camp" +
      `?documentToken=${documentToken}&isMiniature=${isMiniature ? "YES" : ""}`
    );
  }

  DownloadAttestationPresence(token: string) {
    return (
      this.baseURL +
      "/api/v1/espaceperso/download/attestation" +
      `?token=${token}`
    );
  }

  DownloadFacture(token: string) {
    return (
      this.baseURL + "/api/v1/espaceperso/download/facture" + `?token=${token}`
    );
  }
}
