// Code generated by gomacro/typescript/urls_api.go. DO NOT EDIT

export type Int = number & { __opaque__: "Int" };
// registro/controllers/directeurs.LettreImageUploadOut
export interface LettreImageUploadOut {
  location: string;
}

/** Endpoints exposes the HTTP urls handled by the server. */
export class Endpoints {
  constructor(private baseURL: string) {}

  /** Returns an URL */
  EquipiersDownloadFiles(token: string) {
    return (
      this.baseURL + "/api/v1/directeurs/equipiers/files" + `?token=${token}`
    );
  }

  /** Returns an URL */
  LettreImageUpload(token: string) {
    return this.baseURL + "/api/v1/directeurs/lettre-image" + `?token=${token}`;
  }

  /** Returns an URL */
  ParticipantsDownloadListe(token: string) {
    return (
      this.baseURL +
      "/api/v1/directeurs/participants/download-liste" +
      `?token=${token}`
    );
  }

  /** Returns an URL */
  RenderDocumentCamp(documentToken: string, isMiniature: boolean) {
    return (
      this.baseURL +
      "/api/v1/document-camp" +
      `?documentToken=${documentToken}&isMiniature=${isMiniature ? "YES" : ""}`
    );
  }

  /** Returns an URL */
  DownloadAttestationPresence(token: string) {
    return (
      this.baseURL +
      "/api/v1/espaceperso/download/attestation" +
      `?token=${token}`
    );
  }

  /** Returns an URL */
  DownloadFacture(token: string) {
    return (
      this.baseURL + "/api/v1/espaceperso/download/facture" + `?token=${token}`
    );
  }

  /** Returns an URL */
  LoadDocument(key: string) {
    return this.baseURL + "/api/v1/documents" + `?key=${key}`;
  }

  /** Returns an URL */
  LoadMiniature(key: string) {
    return this.baseURL + "/api/v1/documents/miniature" + `?key=${key}`;
  }
}
