package inscriptions

import (
	"math/rand"
	"registro/sql/camps"
	"registro/sql/personnes"
	"registro/sql/shared"
	"time"
)

// Code generated by gomacro/generator/go/randdata. DO NOT EDIT.

func randIdInscription() IdInscription {
	return IdInscription(randint64())
}

func randInscription() Inscription {
	var s Inscription
	s.Id = randIdInscription()
	s.Responsable = randResponsableLegal()
	s.ResponsablePreIdent = randOptIdPersonne()
	s.Message = randstring()
	s.CopiesMails = randper_Mails()
	s.PartageAdressesOK = randbool()
	s.DemandeFondSoutien = randbool()
	s.DateHeure = randtTime()

	return s
}

func randInscriptionParticipant() InscriptionParticipant {
	var s InscriptionParticipant
	s.IdInscription = randIdInscription()
	s.IdCamp = randcam_IdCamp()
	s.PreIdent = randOptIdPersonne()
	s.Nom = randstring()
	s.Prenom = randstring()
	s.DateNaissance = randsha_Date()
	s.Sexe = randper_Sexe()
	s.Nationnalite = randper_Nationnalite()

	return s
}

func randOptIdPersonne() OptIdPersonne {
	var s OptIdPersonne
	s.Id = randper_IdPersonne()
	s.Valid = randbool()

	return s
}

func randResponsableLegal() ResponsableLegal {
	var s ResponsableLegal
	s.Nom = randstring()
	s.Prenom = randstring()
	s.DateNaissance = randsha_Date()
	s.Sexe = randper_Sexe()
	s.Mail = randstring()
	s.Tels = randper_Tels()
	s.Adresse = randstring()
	s.CodePostal = randstring()
	s.Ville = randstring()
	s.Pays = randper_Pays()

	return s
}

func randSlicestring() []string {
	l := 3 + rand.Intn(5)
	out := make([]string, l)
	for i := range out {
		out[i] = randstring()
	}
	return out
}

func randbool() bool {
	i := rand.Int31n(2)
	return i == 1
}

func randcam_IdCamp() camps.IdCamp {
	return camps.IdCamp(randint64())
}

func randint64() int64 {
	return int64(rand.Intn(1000000))
}

func randper_IdPersonne() personnes.IdPersonne {
	return personnes.IdPersonne(randint64())
}

func randper_Mails() personnes.Mails {
	return personnes.Mails(randSlicestring())
}

func randper_Nationnalite() personnes.Nationnalite {
	choix := [...]personnes.Nationnalite{personnes.Autre, personnes.Francaise, personnes.Suisse}
	i := rand.Intn(len(choix))
	return choix[i]
}

func randper_Pays() personnes.Pays {
	return personnes.Pays(randstring())
}

func randper_Sexe() personnes.Sexe {
	choix := [...]personnes.Sexe{personnes.Empty, personnes.Woman, personnes.Man}
	i := rand.Intn(len(choix))
	return choix[i]
}

func randper_Tels() personnes.Tels {
	return personnes.Tels(randSlicestring())
}

func randsha_Date() shared.Date {
	return shared.Date(randtDate())
}

var letterRunes2 = []rune("azertyuiopqsdfghjklmwxcvbn123456789é@!?&èïab ")

func randstring() string {
	b := make([]rune, 10)
	maxLength := len(letterRunes2)
	for i := range b {
		b[i] = letterRunes2[rand.Intn(maxLength)]
	}
	return string(b)
}

func randtDate() time.Time {
	return time.Unix(int64(rand.Int31()), 5)
}

func randtTime() time.Time {
	return time.Unix(int64(rand.Int31()), 5)
}
