package dons

import (
	"math/rand"
	"registro/sql/dossiers"
	"registro/sql/personnes"
	"registro/sql/shared"
	"time"
)

// Code generated by gomacro/generator/go/randdata. DO NOT EDIT.

func randDon() Don {
	var s Don
	s.Id = randIdDon()
	s.IdPersonne = randsha_OptID_per_IdPersonne()
	s.IdOrganisme = randsha_OptID_IdOrganisme()
	s.Montant = randdos_Montant()
	s.ModePaiement = randdos_ModePaiement()
	s.Date = randsha_Date()
	s.Affectation = randstring()
	s.Details = randstring()
	s.Remercie = randbool()

	return s
}

func randIdDon() IdDon {
	return IdDon(randint64())
}

func randIdOrganisme() IdOrganisme {
	return IdOrganisme(randint64())
}

func randOrganisme() Organisme {
	var s Organisme
	s.Id = randIdOrganisme()
	s.Nom = randstring()
	s.Mail = randstring()
	s.Adresse = randstring()
	s.CodePostal = randstring()
	s.Ville = randstring()
	s.Pays = randper_Pays()

	return s
}

func randbool() bool {
	i := rand.Int31n(2)
	return i == 1
}

func randdos_Currency() dossiers.Currency {
	choix := [...]dossiers.Currency{dossiers.Euros, dossiers.FrancsSuisse}
	i := rand.Intn(len(choix))
	return choix[i]
}

func randdos_ModePaiement() dossiers.ModePaiement {
	choix := [...]dossiers.ModePaiement{dossiers.Cheque, dossiers.EnLigne, dossiers.Virement, dossiers.Especes, dossiers.Ancv, dossiers.Helloasso}
	i := rand.Intn(len(choix))
	return choix[i]
}

func randdos_Montant() dossiers.Montant {
	var s dossiers.Montant
	s.Cent = randint()
	s.Currency = randdos_Currency()

	return s
}

func randint() int {
	return int(rand.Intn(1000000))
}

func randint64() int64 {
	return int64(rand.Intn(1000000))
}

func randper_IdPersonne() personnes.IdPersonne {
	return personnes.IdPersonne(randint64())
}

func randper_Pays() personnes.Pays {
	return personnes.Pays(randstring())
}

func randsha_Date() shared.Date {
	return shared.Date(randtDate())
}

func randsha_OptID_IdOrganisme() shared.OptID[IdOrganisme] {
	var s shared.OptID[IdOrganisme]
	s.Id = randIdOrganisme()
	s.Valid = randbool()

	return s
}

func randsha_OptID_per_IdPersonne() shared.OptID[personnes.IdPersonne] {
	var s shared.OptID[personnes.IdPersonne]
	s.Id = randper_IdPersonne()
	s.Valid = randbool()

	return s
}

var letterRunes2 = []rune("azertyuiopqsdfghjklmwxcvbn123456789é@!?&èïab ")

func randstring() string {
	b := make([]rune, 10)
	maxLength := len(letterRunes2)
	for i := range b {
		b[i] = letterRunes2[rand.Intn(maxLength)]
	}
	return string(b)
}

func randtDate() time.Time {
	return time.Unix(int64(rand.Int31()), 5)
}
