-- generated by make_sql.go DO NOT EDIT.

ALTER TABLE participants
    ADD FOREIGN KEY (IdCamp) REFERENCES camps;

ALTER TABLE participants
    ADD FOREIGN KEY (IdPersonne) REFERENCES personnes;

ALTER TABLE personnes
    ADD CONSTRAINT FicheSanitaire_gomacro CHECK (gomacro_validate_json_pers_FicheSanitaire (FicheSanitaire));

