-- generated by make_sql.go DO NOT EDIT.

ALTER TABLE fichesanitaires
    ADD UNIQUE (IdPersonne);

ALTER TABLE dossiers
    ADD FOREIGN KEY (IdPersonne) REFERENCES personnes;

ALTER TABLE fichesanitaires
    ADD FOREIGN KEY (IdPersonne) REFERENCES personnes ON DELETE CASCADE;

ALTER TABLE participants
    ADD FOREIGN KEY (IdCamp) REFERENCES camps ON DELETE CASCADE;

ALTER TABLE participants
    ADD FOREIGN KEY (IdPersonne) REFERENCES personnes ON DELETE CASCADE;

ALTER TABLE participants
    ADD CONSTRAINT Remises_gomacro CHECK (gomacro_validate_json_doss_Remises (Remises));

ALTER TABLE equipiers
    ADD UNIQUE (IdCamp, IdPersonne);

ALTER TABLE lettredirecteurs
    ADD UNIQUE (IdCamp);

ALTER TABLE fichesanitaires
    ADD CONSTRAINT Medecin_gomacro CHECK (gomacro_validate_json_pers_Medecin (Medecin));

ALTER TABLE paiements
    ADD FOREIGN KEY (IdDossier) REFERENCES dossiers ON DELETE CASCADE;

ALTER TABLE participants
    ADD FOREIGN KEY (IdDossier) REFERENCES dossiers ON DELETE CASCADE;

ALTER TABLE equipiers
    ADD FOREIGN KEY (IdCamp) REFERENCES camps;

ALTER TABLE equipiers
    ADD FOREIGN KEY (IdPersonne) REFERENCES personnes ON DELETE CASCADE;

ALTER TABLE equipiers
    ADD CONSTRAINT Presence_gomacro CHECK (gomacro_validate_json_shar_OptionnalPlage (Presence));

ALTER TABLE equipiers
    ADD CONSTRAINT Roles_gomacro CHECK (gomacro_validate_json_array_camp_Role (Roles));

ALTER TABLE fichesanitaires
    ADD CONSTRAINT Allergies_gomacro CHECK (gomacro_validate_json_pers_Allergies (Allergies));

ALTER TABLE fichesanitaires
    ADD CONSTRAINT Maladies_gomacro CHECK (gomacro_validate_json_pers_Maladies (Maladies));

ALTER TABLE sondages
    ADD UNIQUE (IdCamp, IdDossier);

