-- generated by make_sql.go DO NOT EDIT.

CREATE TABLE camps (
    Id serial PRIMARY KEY,
    Nom text NOT NULL,
    DateDebut date NOT NULL,
    Duree integer NOT NULL,
    Agrement text NOT NULL
);

CREATE TABLE participants (
    Id serial PRIMARY KEY,
    IdCamp integer NOT NULL,
    IdPersonne integer NOT NULL
);

CREATE TABLE personnes (
    Id serial PRIMARY KEY,
    Nom text NOT NULL,
    NomJeuneFille text NOT NULL,
    Prenom text NOT NULL,
    DateNaissance date NOT NULL,
    VilleNaissance text NOT NULL,
    DepartementNaissance text NOT NULL,
    Sexe integer CHECK (Sexe IN (2, 1)) NOT NULL,
    Tels text[],
    Mail text NOT NULL,
    Adresse text NOT NULL,
    CodePostal text NOT NULL,
    Ville text NOT NULL,
    Pays text NOT NULL,
    SecuriteSociale text NOT NULL,
    Profession text NOT NULL,
    Etudiant boolean NOT NULL,
    Fonctionnaire boolean NOT NULL,
    Diplome integer CHECK (Diplome IN (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19)) NOT NULL,
    Approfondissement integer CHECK (Approfondissement IN (0, 1, 2, 3, 4, 5)) NOT NULL,
    FicheSanitaire jsonb NOT NULL,
    IsTemp boolean NOT NULL
);

