-- generated by make_sql.go DO NOT EDIT.

ALTER TABLE fichesanitaires
    ADD UNIQUE (IdPersonne);

ALTER TABLE fichesanitaires
    ADD FOREIGN KEY (IdPersonne) REFERENCES personnes ON DELETE CASCADE;

ALTER TABLE fichesanitaires
    ADD CONSTRAINT Allergies_gomacro CHECK (gomacro_validate_json_pers_Allergies (Allergies));

ALTER TABLE fichesanitaires
    ADD CONSTRAINT Maladies_gomacro CHECK (gomacro_validate_json_pers_Maladies (Maladies));

ALTER TABLE fichesanitaires
    ADD CONSTRAINT Medecin_gomacro CHECK (gomacro_validate_json_pers_Medecin (Medecin));

ALTER TABLE tauxs
    ADD UNIQUE (Label);

ALTER TABLE tauxs
    ADD CHECK (Euros = 1000);

ALTER TABLE dossiers
    ADD UNIQUE (Id, IdTaux);

ALTER TABLE dossiers
    ADD FOREIGN KEY (IdResponsable) REFERENCES personnes;

ALTER TABLE dossiers
    ADD FOREIGN KEY (IdTaux) REFERENCES tauxs;

ALTER TABLE paiements
    ADD FOREIGN KEY (IdDossier) REFERENCES dossiers ON DELETE CASCADE;

ALTER TABLE camps
    ADD UNIQUE (Id, IdTaux);

ALTER TABLE camps
    ADD FOREIGN KEY (IdTaux) REFERENCES tauxs;

ALTER TABLE lettredirecteurs
    ADD UNIQUE (IdCamp);

ALTER TABLE lettredirecteurs
    ADD FOREIGN KEY (IdCamp) REFERENCES camps ON DELETE CASCADE;

ALTER TABLE participants
    ADD FOREIGN KEY (IdCamp, IdTaux) REFERENCES camps (Id, IdTaux);

ALTER TABLE participants
    ADD FOREIGN KEY (IdDossier, IdTaux) REFERENCES dossiers (Id, IdTaux) ON DELETE CASCADE;

ALTER TABLE participants
    ADD UNIQUE (Id, IdCamp);

ALTER TABLE participants
    ADD FOREIGN KEY (IdCamp) REFERENCES camps;

ALTER TABLE participants
    ADD FOREIGN KEY (IdPersonne) REFERENCES personnes;

ALTER TABLE participants
    ADD FOREIGN KEY (IdDossier) REFERENCES dossiers ON DELETE CASCADE;

ALTER TABLE participants
    ADD FOREIGN KEY (IdTaux) REFERENCES tauxs;

ALTER TABLE groupes
    ADD UNIQUE (IdCamp, Nom);

ALTER TABLE groupes
    ADD UNIQUE (Id, IdCamp);

ALTER TABLE groupes
    ADD FOREIGN KEY (IdCamp) REFERENCES camps ON DELETE CASCADE;

ALTER TABLE groupe_participants
    ADD UNIQUE (IdParticipant);

ALTER TABLE groupe_participants
    ADD UNIQUE (IdParticipant, IdCamp);

ALTER TABLE groupe_participants
    ADD FOREIGN KEY (IdParticipant, IdCamp) REFERENCES participants (Id, IdCamp) ON DELETE CASCADE;

ALTER TABLE groupe_participants
    ADD FOREIGN KEY (IdGroupe, IdCamp) REFERENCES groupes (Id, IdCamp) ON DELETE CASCADE;

ALTER TABLE groupe_participants
    ADD FOREIGN KEY (IdParticipant) REFERENCES participants ON DELETE CASCADE;

ALTER TABLE groupe_participants
    ADD FOREIGN KEY (IdGroupe) REFERENCES groupes ON DELETE CASCADE;

ALTER TABLE groupe_participants
    ADD FOREIGN KEY (IdCamp) REFERENCES camps;

ALTER TABLE equipiers
    ADD UNIQUE (IdCamp, IdPersonne);

CREATE UNIQUE INDEX ON equipiers (IdCamp)
WHERE
    1
    /* Role.Direction */
    = ANY (Roles);

ALTER TABLE equipiers
    ADD FOREIGN KEY (IdCamp) REFERENCES camps ON DELETE CASCADE;

ALTER TABLE equipiers
    ADD FOREIGN KEY (IdPersonne) REFERENCES personnes ON DELETE CASCADE;

ALTER TABLE sondages
    ADD UNIQUE (IdCamp, IdDossier);

ALTER TABLE sondages
    ADD FOREIGN KEY (IdCamp) REFERENCES camps ON DELETE CASCADE;

ALTER TABLE sondages
    ADD FOREIGN KEY (IdDossier) REFERENCES dossiers ON DELETE CASCADE;

ALTER TABLE aides
    ADD FOREIGN KEY (IdStructureaide) REFERENCES structureaides;

ALTER TABLE aides
    ADD FOREIGN KEY (IdParticipant) REFERENCES participants ON DELETE CASCADE;

ALTER TABLE camps
    ADD CONSTRAINT Navette_gomacro CHECK (gomacro_validate_json_camp_Navette (Navette));

ALTER TABLE camps
    ADD CONSTRAINT OptionPrix_gomacro CHECK (gomacro_validate_json_camp_OptionPrixCamp (OptionPrix));

ALTER TABLE participants
    ADD CONSTRAINT OptionPrix_gomacro CHECK (gomacro_validate_json_camp_OptionPrixParticipant (OptionPrix));

ALTER TABLE equipiers
    ADD CONSTRAINT Presence_gomacro CHECK (gomacro_validate_json_camp_OptionnalPlage (Presence));

ALTER TABLE participants
    ADD CONSTRAINT Remises_gomacro CHECK (gomacro_validate_json_camp_Remises (Remises));

ALTER TABLE groupes
    ADD CONSTRAINT Plage_gomacro CHECK (gomacro_validate_json_shar_Plage (Plage));

ALTER TABLE demandes
    ADD CONSTRAINT constraint_categorie CHECK (Categorie = 0 OR IdDirecteur IS NULL);

ALTER TABLE demandes
    ADD CONSTRAINT constraint_maxdocs CHECK (MaxDocs >= 1);

CREATE UNIQUE INDEX ON demandes (Categorie)
WHERE
    Categorie <> 0;

ALTER TABLE demandes
    ADD FOREIGN KEY (IdFile) REFERENCES files;

ALTER TABLE demandes
    ADD FOREIGN KEY (IdDirecteur) REFERENCES personnes ON DELETE CASCADE;

ALTER TABLE demande_equipiers
    ADD UNIQUE (IdEquipier, IdDemande);

ALTER TABLE demande_equipiers
    ADD FOREIGN KEY (IdEquipier) REFERENCES equipiers ON DELETE CASCADE;

ALTER TABLE demande_equipiers
    ADD FOREIGN KEY (IdDemande) REFERENCES demandes;

ALTER TABLE demande_camps
    ADD UNIQUE (IdCamp, IdDemande);

ALTER TABLE demande_camps
    ADD FOREIGN KEY (IdCamp) REFERENCES camps ON DELETE CASCADE;

ALTER TABLE demande_camps
    ADD FOREIGN KEY (IdDemande) REFERENCES demandes;

ALTER TABLE file_camps
    ADD UNIQUE (IdFile);

CREATE UNIQUE INDEX ON file_camps (IdCamp)
WHERE
    IsLettre IS TRUE;

ALTER TABLE file_camps
    ADD FOREIGN KEY (IdFile) REFERENCES files ON DELETE CASCADE;

ALTER TABLE file_camps
    ADD FOREIGN KEY (IdCamp) REFERENCES camps;

ALTER TABLE file_personnes
    ADD UNIQUE (IdFile);

ALTER TABLE file_personnes
    ADD FOREIGN KEY (IdFile) REFERENCES files ON DELETE CASCADE;

ALTER TABLE file_personnes
    ADD FOREIGN KEY (IdPersonne) REFERENCES personnes;

ALTER TABLE file_personnes
    ADD FOREIGN KEY (IdDemande) REFERENCES demandes;

ALTER TABLE file_aides
    ADD UNIQUE (IdFile);

ALTER TABLE file_aides
    ADD UNIQUE (IdAide);

ALTER TABLE file_aides
    ADD FOREIGN KEY (IdFile) REFERENCES files ON DELETE CASCADE;

ALTER TABLE file_aides
    ADD FOREIGN KEY (IdAide) REFERENCES aides;

ALTER TABLE inscriptions
    ADD FOREIGN KEY (ResponsablePreIdent) REFERENCES personnes ON DELETE SET NULL;

ALTER TABLE inscription_participants
    ADD FOREIGN KEY (IdInscription) REFERENCES inscriptions ON DELETE CASCADE;

ALTER TABLE inscription_participants
    ADD FOREIGN KEY (IdCamp) REFERENCES camps ON DELETE CASCADE;

ALTER TABLE inscription_participants
    ADD FOREIGN KEY (PreIdent) REFERENCES personnes ON DELETE SET NULL;

ALTER TABLE inscriptions
    ADD CONSTRAINT Responsable_gomacro CHECK (gomacro_validate_json_insc_ResponsableLegal (Responsable));

