// Code generated by gomacro/typescript/axios_api.go. DO NOT EDIT

import type { AxiosResponse } from "axios";
import Axios from "axios";

export type Ar4_Int = [Int, Int, Int, Int];

// AAAA-MM-YY date format
export type Date_ = string & { __opaque__: "Date" };

export type Int = number & { __opaque__: "Int" };

// ISO date-time string
export type Time = string & { __opaque__: "Time" };

// registro/controllers/backoffice.AidesCreateIn
export interface AidesCreateIn {
  IdParticipant: IdParticipant;
  IdStructure: IdStructureaide;
}
// registro/controllers/backoffice.CampHeader
export interface CampHeader {
  Camp: CampExt;
  Taux: Taux;
  Stats: StatistiquesInscrits;
}
// registro/controllers/backoffice.CampsCreateManyIn
export interface CampsCreateManyIn {
  Taux: Taux;
  Count: Int;
}
// registro/controllers/backoffice.CampsSetTauxIn
export interface CampsSetTauxIn {
  IdCamp: IdCamp;
  Taux: Taux;
}
// registro/controllers/backoffice.DossierDetails
export interface DossierDetails {
  Dossier: DossierExt;
  EspacepersoURL: string;
  VirementCode: string;
}
// registro/controllers/backoffice.DossierHeader
export interface DossierHeader {
  Id: IdDossier;
  Responsable: string;
  Participants: string;
  NewMessages: Int;
}
// registro/controllers/backoffice.DossiersMergeIn
export interface DossiersMergeIn {
  From: IdDossier;
  To: IdDossier;
  Notifie: boolean;
}
// registro/controllers/backoffice.DossiersUpdateOut
export interface DossiersUpdateOut {
  Responsable: string;
}
// registro/controllers/backoffice.EventsSendMessageIn
export interface EventsSendMessageIn {
  IdDossier: IdDossier;
  Contenu: string;
}
// registro/controllers/backoffice.IdentTarget
export interface IdentTarget {
  IdTemporaire: IdPersonne;
  Rattache: boolean;
  RattacheTo: IdPersonne;
}
// registro/controllers/backoffice.Inscription
export interface Inscription {
  Dossier: Dossier;
  Message: string;
  Responsable: Personne;
  Participants: ParticipantExt[] | null;
}
// registro/controllers/backoffice.InscriptionIdentifieIn
export interface InscriptionIdentifieIn {
  IdDossier: IdDossier;
  Target: IdentTarget;
}
// registro/controllers/backoffice.ParticipantsCreateIn
export interface ParticipantsCreateIn {
  IdDossier: IdDossier;
  IdCamp: IdCamp;
  IdPersonne: IdPersonne;
}
// registro/controllers/backoffice.QueryAttente
export const QueryAttente = {
  EmptyQA: 0,
  AvecAttente: 1,
  AvecInscrits: 2,
  AvecAttenteOnly: 3,
} as const;
export type QueryAttente = (typeof QueryAttente)[keyof typeof QueryAttente];

export const QueryAttenteLabels: { [key in QueryAttente]: string } = {
  [QueryAttente.EmptyQA]: "Indifférent",
  [QueryAttente.AvecAttente]: "Avec liste d'attente",
  [QueryAttente.AvecInscrits]: "Avec inscrits",
  [QueryAttente.AvecAttenteOnly]: "Seulement avec liste d'attente",
};

// registro/controllers/backoffice.QueryReglement
export const QueryReglement = {
  EmptyQR: 0,
  Zero: 1,
  Partiel: 2,
  Total: 3,
} as const;
export type QueryReglement =
  (typeof QueryReglement)[keyof typeof QueryReglement];

export const QueryReglementLabels: { [key in QueryReglement]: string } = {
  [QueryReglement.EmptyQR]: "Indifférent",
  [QueryReglement.Zero]: "Non commencé",
  [QueryReglement.Partiel]: "En cours",
  [QueryReglement.Total]: "Complété",
};

// registro/controllers/backoffice.SearchDossierIn
export interface SearchDossierIn {
  Pattern: string;
  IdCamp: OptIdCamp;
  Attente: QueryAttente;
  Reglement: QueryReglement;
}
// registro/controllers/backoffice.SearchDossierOut
export interface SearchDossierOut {
  Dossiers: DossierHeader[] | null;
  Total: Int;
}
// registro/controllers/logic.AccuseReception
export type AccuseReception = Record<string, never>;
// registro/controllers/logic.AideResolved
export interface AideResolved {
  Structure: string;
  Montant: Montant;
}
// registro/controllers/logic.Attestation
export interface Attestation {
  Distribution: Distribution;
  IsPresence: boolean;
}
// registro/controllers/logic.BilanFinancesPub
export interface BilanFinancesPub {
  Inscrits: { [key in IdParticipant]: BilanParticipantPub } | null;
  Demande: string;
  Recu: string;
  Restant: string;
  Statut: StatutPaiement;
}
// registro/controllers/logic.BilanParticipantPub
export interface BilanParticipantPub {
  AvecOption: Montant;
  AvecOptionDescription: string;
  Remises: Remises;
  Aides: AideResolved[] | null;
  AvecAides: string;
  Net: string;
}
// registro/controllers/logic.CampDocs
export interface CampDocs {
  IdCamp: IdCamp;
  CampLabel: string;
}
// registro/controllers/logic.CampItem
export interface CampItem {
  Id: IdCamp;
  Label: string;
  IsOld: boolean;
}
// registro/controllers/logic.DossierExt
export interface DossierExt {
  Dossier: Dossier;
  Responsable: string;
  Participants: ParticipantExt[] | null;
  Aides: { [key in IdParticipant]: Aides } | null;
  Events: Events;
  Paiements: Paiements;
  Bilan: BilanFinancesPub;
}
// registro/controllers/logic.Event
export interface Event {
  Id: IdEvent;
  Created: Time;
  Content: EventContent;
}

export const EventContentKind = {
  AccuseReception: "AccuseReception",
  Attestation: "Attestation",
  CampDocs: "CampDocs",
  Facture: "Facture",
  Message: "Message",
  PlaceLiberee: "PlaceLiberee",
  Sondage: "Sondage",
  Supprime: "Supprime",
} as const;
export type EventContentKind =
  (typeof EventContentKind)[keyof typeof EventContentKind];

// registro/controllers/logic.EventContent
export type EventContent =
  | { Kind: "AccuseReception"; Data: AccuseReception }
  | { Kind: "Attestation"; Data: Attestation }
  | { Kind: "CampDocs"; Data: CampDocs }
  | { Kind: "Facture"; Data: Facture }
  | { Kind: "Message"; Data: Message }
  | { Kind: "PlaceLiberee"; Data: PlaceLiberee }
  | { Kind: "Sondage"; Data: Sondage }
  | { Kind: "Supprime"; Data: Supprime };

// registro/controllers/logic.Events
export type Events = Event[] | null;
// registro/controllers/logic.Facture
export type Facture = Record<string, never>;
// registro/controllers/logic.Message
export interface Message {
  Message: EventMessage;
  OrigineCampLabel: string;
  VuParCamps: string[] | null;
}
// registro/controllers/logic.PlaceLiberee
export interface PlaceLiberee {
  IdParticipant: IdParticipant;
  IdCamp: IdCamp;
  ParticipantLabel: string;
  CampLabel: string;
}
// registro/controllers/logic.Sondage
export interface Sondage {
  IdCamp: IdCamp;
  CampLabel: string;
}
// registro/controllers/logic.StatutPaiement
export const StatutPaiement = {
  Complet: 3,
  EnCours: 2,
  NonCommence: 1,
} as const;
export type StatutPaiement =
  (typeof StatutPaiement)[keyof typeof StatutPaiement];

export const StatutPaiementLabels: { [key in StatutPaiement]: string } = {
  [StatutPaiement.Complet]: "",
  [StatutPaiement.EnCours]: "",
  [StatutPaiement.NonCommence]: "",
};

// registro/controllers/logic.Supprime
export type Supprime = Record<string, never>;
// registro/controllers/search.PersonneHeader
export interface PersonneHeader {
  Id: IdPersonne;
  Label: string;
  Sexe: Sexe;
  DateNaissance: Date;
}
// registro/controllers/search.ScoredPersonne
export interface ScoredPersonne {
  ScorePercent: Int;
  Personne: PersonneHeader;
}
// registro/sql/camps.Aide
export interface Aide {
  Id: IdAide;
  IdStructureaide: IdStructureaide;
  IdParticipant: IdParticipant;
  Valide: boolean;
  Valeur: Montant;
  ParJour: boolean;
  NbJoursMax: Int;
}
// registro/sql/camps.Aides
export type Aides = { [key in IdAide]: Aide } | null;
// registro/sql/camps.Bus
export const Bus = {
  NoBus: 0,
  Aller: 1,
  Retour: 2,
  AllerRetour: 3,
} as const;
export type Bus = (typeof Bus)[keyof typeof Bus];

export const BusLabels: { [key in Bus]: string } = {
  [Bus.NoBus]: "",
  [Bus.Aller]: "",
  [Bus.Retour]: "",
  [Bus.AllerRetour]: "",
};

// registro/sql/camps.Camp
export interface Camp {
  Id: IdCamp;
  IdTaux: IdTaux;
  Nom: string;
  DateDebut: Date;
  Duree: Int;
  Lieu: string;
  Agrement: string;
  Description: string;
  Navette: Navette;
  Places: Int;
  AgeMin: Int;
  AgeMax: Int;
  NeedEquilibreGF: boolean;
  Ouvert: boolean;
  Prix: Montant;
  OptionPrix: OptionPrixCamp;
  OptionQuotientFamilial: PrixQuotientFamilial;
  Password: string;
}
// registro/sql/camps.CampExt
export interface CampExt {
  Camp: Camp;
  IsTerminated: boolean;
}
// registro/sql/camps.IdAide
export type IdAide = Int;
// registro/sql/camps.IdCamp
export type IdCamp = Int;
// registro/sql/camps.IdParticipant
export type IdParticipant = Int;
// registro/sql/camps.IdStructureaide
export type IdStructureaide = Int;
// registro/sql/camps.Jours
export type Jours = Int[] | null;
// registro/sql/camps.ListeAttente
export const ListeAttente = {
  AStatuer: 0,
  AttenteProfilInvalide: 1,
  Refuse: 2,
  AttenteCampComplet: 3,
  EnAttenteReponse: 4,
  Inscrit: 5,
} as const;
export type ListeAttente = (typeof ListeAttente)[keyof typeof ListeAttente];

export const ListeAttenteLabels: { [key in ListeAttente]: string } = {
  [ListeAttente.AStatuer]: "",
  [ListeAttente.AttenteProfilInvalide]: "",
  [ListeAttente.Refuse]: "",
  [ListeAttente.AttenteCampComplet]: "",
  [ListeAttente.EnAttenteReponse]: "",
  [ListeAttente.Inscrit]: "",
};

// registro/sql/camps.Navette
export interface Navette {
  Actif: boolean;
  Commentaire: string;
}
// registro/sql/camps.OptionPrixCamp
export interface OptionPrixCamp {
  Active: OptionPrixKind;
  Statuts: PrixParStatut[] | null;
  Jours: Int[] | null;
}
// registro/sql/camps.OptionPrixKind
export const OptionPrixKind = {
  NoOption: 0,
  PrixStatut: 1,
  PrixJour: 2,
} as const;
export type OptionPrixKind =
  (typeof OptionPrixKind)[keyof typeof OptionPrixKind];

export const OptionPrixKindLabels: { [key in OptionPrixKind]: string } = {
  [OptionPrixKind.NoOption]: "Aucune",
  [OptionPrixKind.PrixStatut]: "Prix par statut",
  [OptionPrixKind.PrixJour]: "Prix à la journée",
};

// registro/sql/camps.OptionPrixParticipant
export interface OptionPrixParticipant {
  IdStatut: Int;
  Jour: Jours;
}
// registro/sql/camps.Participant
export interface Participant {
  Id: IdParticipant;
  IdCamp: IdCamp;
  IdPersonne: IdPersonne;
  IdDossier: IdDossier;
  IdTaux: IdTaux;
  Statut: ListeAttente;
  Remises: Remises;
  QuotientFamilial: Int;
  OptionPrix: OptionPrixParticipant;
  Details: string;
  Bus: Bus;
}
// registro/sql/camps.ParticipantExt
export interface ParticipantExt {
  Camp: Camp;
  Participant: Participant;
  Personne: Personne;
}
// registro/sql/camps.PrixParStatut
export interface PrixParStatut {
  Id: Int;
  Prix: Int;
  Label: string;
  Description: string;
}
// registro/sql/camps.PrixQuotientFamilial
export type PrixQuotientFamilial = Ar4_Int;
// registro/sql/camps.Remises
export interface Remises {
  ReducEquipiers: Int;
  ReducEnfants: Int;
  ReducSpeciale: Montant;
}
// registro/sql/camps.StatistiquesInscrits
export interface StatistiquesInscrits {
  Inscriptions: Int;
  InscriptionsFilles: Int;
  InscriptionsSuisses: Int;
  Valides: Int;
  ValidesFilles: Int;
  ValidesSuisses: Int;
  Refus: Int;
  AStatuer: Int;
  Exceptions: Int;
  Attente: Int;
}
// registro/sql/camps.Structureaide
export interface Structureaide {
  Id: IdStructureaide;
  Nom: string;
  Immatriculation: string;
  Adresse: string;
  CodePostal: string;
  Ville: string;
  Telephone: Tel;
  Info: string;
}
// registro/sql/camps.Structureaides
export type Structureaides = { [key in IdStructureaide]: Structureaide } | null;
// registro/sql/dossiers.Currency
export const Currency = {
  Euros: 0,
  FrancsSuisse: 1,
} as const;
export type Currency = (typeof Currency)[keyof typeof Currency];

export const CurrencyLabels: { [key in Currency]: string } = {
  [Currency.Euros]: "€",
  [Currency.FrancsSuisse]: "CHF",
};

// registro/sql/dossiers.Dossier
export interface Dossier {
  Id: IdDossier;
  IdTaux: IdTaux;
  IdResponsable: IdPersonne;
  CopiesMails: Mails;
  PartageAdressesOK: boolean;
  DemandeFondSoutien: boolean;
  IsValidated: boolean;
  MomentInscription: Time;
  LastSeenEspaceperso: Time;
  KeyV1: string;
}
// registro/sql/dossiers.IdDossier
export type IdDossier = Int;
// registro/sql/dossiers.IdPaiement
export type IdPaiement = Int;
// registro/sql/dossiers.IdTaux
export type IdTaux = Int;
// registro/sql/dossiers.ModePaiement
export const ModePaiement = {
  Cheque: 0,
  EnLigne: 1,
  Virement: 2,
  Especes: 3,
  Ancv: 4,
  Helloasso: 5,
} as const;
export type ModePaiement = (typeof ModePaiement)[keyof typeof ModePaiement];

export const ModePaiementLabels: { [key in ModePaiement]: string } = {
  [ModePaiement.Cheque]: "Chèque",
  [ModePaiement.EnLigne]: "Carte bancaire (en ligne)",
  [ModePaiement.Virement]: "Virement",
  [ModePaiement.Especes]: "Espèces",
  [ModePaiement.Ancv]: "ANCV",
  [ModePaiement.Helloasso]: "Helloasso",
};

// registro/sql/dossiers.Montant
export interface Montant {
  Cent: Int;
  Currency: Currency;
}
// registro/sql/dossiers.Paiement
export interface Paiement {
  Id: IdPaiement;
  IdDossier: IdDossier;
  IsRemboursement: boolean;
  Montant: Montant;
  Payeur: string;
  Mode: ModePaiement;
  Time: Time;
  Label: string;
  Details: string;
}
// registro/sql/dossiers.Paiements
export type Paiements = { [key in IdPaiement]: Paiement } | null;
// registro/sql/dossiers.Taux
export interface Taux {
  Id: IdTaux;
  Label: string;
  Euros: Int;
  FrancsSuisse: Int;
}
// registro/sql/dossiers.Tauxs
export type Tauxs = { [key in IdTaux]: Taux } | null;
// registro/sql/events.Distribution
export const Distribution = {
  DEspacePerso: 0,
  DMail: 1,
  DMailAndDownloaded: 2,
} as const;
export type Distribution = (typeof Distribution)[keyof typeof Distribution];

export const DistributionLabels: { [key in Distribution]: string } = {
  [Distribution.DEspacePerso]: "Téléchargée depuis l'espace de suivi",
  [Distribution.DMail]: "Notifiée par courriel",
  [Distribution.DMailAndDownloaded]: "Téléchargée après notification",
};

// registro/sql/events.EventMessage
export interface EventMessage {
  IdEvent: IdEvent;
  Contenu: string;
  Origine: MessageOrigine;
  OrigineCamp: OptIdCamp;
  VuBackoffice: boolean;
  VuEspaceperso: boolean;
}
// registro/sql/events.IdEvent
export type IdEvent = Int;
// registro/sql/events.MessageOrigine
export const MessageOrigine = {
  FromEspaceperso: 0,
  FromBackoffice: 1,
  FromDirecteur: 2,
} as const;
export type MessageOrigine =
  (typeof MessageOrigine)[keyof typeof MessageOrigine];

export const MessageOrigineLabels: { [key in MessageOrigine]: string } = {
  [MessageOrigine.FromEspaceperso]: "",
  [MessageOrigine.FromBackoffice]: "",
  [MessageOrigine.FromDirecteur]: "",
};

// registro/sql/events.OptIdCamp
export interface OptIdCamp {
  Id: IdCamp;
  Valid: boolean;
}
// registro/sql/personnes.Approfondissement
export const Approfondissement = {
  AAucun: 0,
  AAutre: 1,
  ASb: 2,
  ACanoe: 3,
  AVoile: 4,
  AMoto: 5,
} as const;
export type Approfondissement =
  (typeof Approfondissement)[keyof typeof Approfondissement];

export const ApprofondissementLabels: { [key in Approfondissement]: string } = {
  [Approfondissement.AAucun]: "Non effectué",
  [Approfondissement.AAutre]: "Approfondissement",
  [Approfondissement.ASb]: "Surveillant de baignade",
  [Approfondissement.ACanoe]: "Canoë - Kayak",
  [Approfondissement.AVoile]: "Voile",
  [Approfondissement.AMoto]: "Loisirs motocyclistes",
};

// registro/sql/personnes.Departement
export type Departement = string;
// registro/sql/personnes.Diplome
export const Diplome = {
  DAucun: 0,
  DBafa: 1,
  DBafaStag: 2,
  DBafd: 3,
  DBafdStag: 4,
  DCap: 5,
  DAssSociale: 6,
  DEducSpe: 7,
  DMonEduc: 8,
  DInstit: 9,
  DProf: 10,
  DAgreg: 11,
  DBjeps: 12,
  DDut: 13,
  DEje: 14,
  DDeug: 15,
  DStaps: 16,
  DBapaat: 17,
  DBeatep: 18,
  DZzautre: 19,
} as const;
export type Diplome = (typeof Diplome)[keyof typeof Diplome];

export const DiplomeLabels: { [key in Diplome]: string } = {
  [Diplome.DAucun]: "Aucun",
  [Diplome.DBafa]: "BAFA Titulaire",
  [Diplome.DBafaStag]: "BAFA Stagiaire",
  [Diplome.DBafd]: "BAFD titulaire",
  [Diplome.DBafdStag]: "BAFD stagiaire",
  [Diplome.DCap]: "CAP petit enfance",
  [Diplome.DAssSociale]: "Assitante Sociale",
  [Diplome.DEducSpe]: "Educ. spé.",
  [Diplome.DMonEduc]: "Moniteur educateur",
  [Diplome.DInstit]: "Professeur des écoles",
  [Diplome.DProf]: "Enseignant du secondaire",
  [Diplome.DAgreg]: "Agrégé",
  [Diplome.DBjeps]: "BPJEPS",
  [Diplome.DDut]: "DUT carrière sociale",
  [Diplome.DEje]: "EJE",
  [Diplome.DDeug]: "DEUG",
  [Diplome.DStaps]: "STAPS",
  [Diplome.DBapaat]: "BAPAAT",
  [Diplome.DBeatep]: "BEATEP",
  [Diplome.DZzautre]: "AUTRE",
};

// registro/sql/personnes.IdPersonne
export type IdPersonne = Int;
// registro/sql/personnes.Mails
export type Mails = string[] | null;
// registro/sql/personnes.Nationnalite
export const Nationnalite = {
  Autre: 0,
  Francaise: 1,
  Suisse: 2,
} as const;
export type Nationnalite = (typeof Nationnalite)[keyof typeof Nationnalite];

export const NationnaliteLabels: { [key in Nationnalite]: string } = {
  [Nationnalite.Autre]: "Autre",
  [Nationnalite.Francaise]: "Française",
  [Nationnalite.Suisse]: "Suisse",
};

// registro/sql/personnes.Pays
export type Pays = string;
// registro/sql/personnes.Personne
export interface Personne {
  Id: IdPersonne;
  Nom: string;
  Prenom: string;
  Sexe: Sexe;
  DateNaissance: Date;
  VilleNaissance: string;
  DepartementNaissance: Departement;
  Nationnalite: Nationnalite;
  Tels: Tels;
  Mail: string;
  Adresse: string;
  CodePostal: string;
  Ville: string;
  Pays: Pays;
  SecuriteSociale: string;
  NomJeuneFille: string;
  Profession: string;
  Etudiant: boolean;
  Fonctionnaire: boolean;
  Diplome: Diplome;
  Approfondissement: Approfondissement;
  Publicite: Publicite;
  IsTemp: boolean;
}
// registro/sql/personnes.Publicite
export interface Publicite {
  VersionPapier: boolean;
  PubHiver: boolean;
  PubEte: boolean;
  EchoRocher: boolean;
  Eonews: boolean;
}
// registro/sql/personnes.Sexe
export const Sexe = {
  Empty: 0,
  Woman: 1,
  Man: 2,
} as const;
export type Sexe = (typeof Sexe)[keyof typeof Sexe];

export const SexeLabels: { [key in Sexe]: string } = {
  [Sexe.Empty]: "",
  [Sexe.Woman]: "Femme",
  [Sexe.Man]: "Homme",
};

// registro/sql/personnes.Tel
export type Tel = string;
// registro/sql/personnes.Tels
export type Tels = string[] | null;
// registro/sql/shared.Date
export type Date = Date_;

/** AbstractAPI provides auto-generated API calls and should be used 
		as base class for an app controller.
	*/
export abstract class AbstractAPI {
  constructor(
    protected baseUrl: string,
    protected authToken: string,
  ) {}

  protected abstract handleError(error: any): void;

  protected abstract startRequest(): void;

  getHeaders() {
    return { Authorization: "Bearer " + this.authToken };
  }

  /** GetCamps performs the request and handles the error */
  async GetCamps() {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/shared/camps";
    this.startRequest();
    try {
      const rep: AxiosResponse<CampItem[] | null> = await Axios.post(
        fullUrl,
        null,
        { headers: this.getHeaders() },
      );
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** SelectPersonne performs the request and handles the error */
  async SelectPersonne(params: { search: string }) {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/shared/personne";
    this.startRequest();
    try {
      const rep: AxiosResponse<PersonneHeader[] | null> = await Axios.get(
        fullUrl,
        { headers: this.getHeaders(), params: { search: params["search"] } },
      );
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** GetStructureaides performs the request and handles the error */
  async GetStructureaides() {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/shared/structureaides";
    this.startRequest();
    try {
      const rep: AxiosResponse<Structureaides> = await Axios.get(fullUrl, {
        headers: this.getHeaders(),
      });
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** CampsGet performs the request and handles the error */
  async CampsGet() {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/camps";
    this.startRequest();
    try {
      const rep: AxiosResponse<CampHeader[] | null> = await Axios.get(fullUrl, {
        headers: this.getHeaders(),
      });
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** CampsCreate performs the request and handles the error */
  async CampsCreate() {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/camps";
    this.startRequest();
    try {
      const rep: AxiosResponse<CampHeader> = await Axios.put(fullUrl, null, {
        headers: this.getHeaders(),
      });
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** CampsCreateMany performs the request and handles the error */
  async CampsCreateMany(params: CampsCreateManyIn) {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/camps-many";
    this.startRequest();
    try {
      const rep: AxiosResponse<CampHeader[] | null> = await Axios.put(
        fullUrl,
        params,
        { headers: this.getHeaders() },
      );
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** CampsUpdate performs the request and handles the error */
  async CampsUpdate(params: Camp) {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/camps";
    this.startRequest();
    try {
      const rep: AxiosResponse<CampExt> = await Axios.post(fullUrl, params, {
        headers: this.getHeaders(),
      });
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** CampsDelete performs the request and handles the error */
  async CampsDelete(params: { id: Int }) {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/camps";
    this.startRequest();
    try {
      await Axios.delete(fullUrl, {
        headers: this.getHeaders(),
        params: { id: String(params["id"]) },
      });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** CampsGetTaux performs the request and handles the error */
  async CampsGetTaux() {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/camps-taux";
    this.startRequest();
    try {
      const rep: AxiosResponse<Tauxs> = await Axios.get(fullUrl, {
        headers: this.getHeaders(),
      });
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** CampsSetTaux performs the request and handles the error */
  async CampsSetTaux(params: CampsSetTauxIn) {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/camps-taux";
    this.startRequest();
    try {
      const rep: AxiosResponse<CampHeader> = await Axios.post(fullUrl, params, {
        headers: this.getHeaders(),
      });
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** InscriptionsGet performs the request and handles the error */
  async InscriptionsGet() {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/inscriptions";
    this.startRequest();
    try {
      const rep: AxiosResponse<Inscription[] | null> = await Axios.get(
        fullUrl,
        { headers: this.getHeaders() },
      );
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** InscriptionsSearchSimilaires performs the request and handles the error */
  async InscriptionsSearchSimilaires(params: { idPersonne: Int }) {
    const fullUrl =
      this.baseUrl + "/api/v1/backoffice/inscriptions/search-similaires";
    this.startRequest();
    try {
      const rep: AxiosResponse<ScoredPersonne[] | null> = await Axios.get(
        fullUrl,
        {
          headers: this.getHeaders(),
          params: { idPersonne: String(params["idPersonne"]) },
        },
      );
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** InscriptionsIdentifiePersonne performs the request and handles the error */
  async InscriptionsIdentifiePersonne(params: InscriptionIdentifieIn) {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/inscriptions/identifie";
    this.startRequest();
    try {
      const rep: AxiosResponse<Inscription> = await Axios.post(
        fullUrl,
        params,
        { headers: this.getHeaders() },
      );
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** InscriptionsValide performs the request and handles the error */
  async InscriptionsValide(params: { idDossier: Int }) {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/inscriptions/valide";
    this.startRequest();
    try {
      await Axios.post(fullUrl, null, {
        headers: this.getHeaders(),
        params: { idDossier: String(params["idDossier"]) },
      });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** DossiersSearch performs the request and handles the error */
  async DossiersSearch(params: SearchDossierIn) {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/dossiers/search";
    this.startRequest();
    try {
      const rep: AxiosResponse<SearchDossierOut> = await Axios.post(
        fullUrl,
        params,
        { headers: this.getHeaders() },
      );
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** DossiersLoad performs the request and handles the error */
  async DossiersLoad(params: { id: Int }) {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/dossiers";
    this.startRequest();
    try {
      const rep: AxiosResponse<DossierDetails> = await Axios.get(fullUrl, {
        headers: this.getHeaders(),
        params: { id: String(params["id"]) },
      });
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** DossiersCreate performs the request and handles the error */
  async DossiersCreate(params: { idResponsable: Int }) {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/dossiers";
    this.startRequest();
    try {
      const rep: AxiosResponse<DossierHeader> = await Axios.put(fullUrl, null, {
        headers: this.getHeaders(),
        params: { idResponsable: String(params["idResponsable"]) },
      });
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** DossiersUpdate performs the request and handles the error */
  async DossiersUpdate(params: Dossier) {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/dossiers";
    this.startRequest();
    try {
      const rep: AxiosResponse<DossiersUpdateOut> = await Axios.post(
        fullUrl,
        params,
        { headers: this.getHeaders() },
      );
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** DossiersDelete performs the request and handles the error */
  async DossiersDelete(params: { id: Int }) {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/dossiers";
    this.startRequest();
    try {
      await Axios.delete(fullUrl, {
        headers: this.getHeaders(),
        params: { id: String(params["id"]) },
      });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** DossiersMerge performs the request and handles the error */
  async DossiersMerge(params: DossiersMergeIn) {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/dossiers/merge";
    this.startRequest();
    try {
      await Axios.post(fullUrl, params, { headers: this.getHeaders() });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** AidesCreate performs the request and handles the error */
  async AidesCreate(params: AidesCreateIn) {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/aides";
    this.startRequest();
    try {
      const rep: AxiosResponse<Aide> = await Axios.put(fullUrl, params, {
        headers: this.getHeaders(),
      });
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** AidesUpdate performs the request and handles the error */
  async AidesUpdate(params: Aide) {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/aides";
    this.startRequest();
    try {
      await Axios.post(fullUrl, params, { headers: this.getHeaders() });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** AidesDelete performs the request and handles the error */
  async AidesDelete(params: { id: Int }) {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/aides";
    this.startRequest();
    try {
      await Axios.delete(fullUrl, {
        headers: this.getHeaders(),
        params: { id: String(params["id"]) },
      });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** AidesJustificatifUpload performs the request and handles the error */
  async AidesJustificatifUpload(file: File, params: { idAide: Int }) {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/aides/justificatif";
    this.startRequest();
    try {
      const formData = new FormData();
      formData.append("file", file, file.name);
      await Axios.post(fullUrl, formData, {
        headers: this.getHeaders(),
        params: { idAide: String(params["idAide"]) },
      });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** AidesJustificatifDelete performs the request and handles the error */
  async AidesJustificatifDelete(params: { idAide: Int }) {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/aides/justificatif";
    this.startRequest();
    try {
      await Axios.delete(fullUrl, {
        headers: this.getHeaders(),
        params: { idAide: String(params["idAide"]) },
      });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** ParticipantsCreate performs the request and handles the error */
  async ParticipantsCreate(params: ParticipantsCreateIn) {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/participants";
    this.startRequest();
    try {
      const rep: AxiosResponse<Participant> = await Axios.put(fullUrl, params, {
        headers: this.getHeaders(),
      });
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** ParticipantsUpdate performs the request and handles the error */
  async ParticipantsUpdate(params: Participant) {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/participants";
    this.startRequest();
    try {
      await Axios.post(fullUrl, params, { headers: this.getHeaders() });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** ParticipantsDelete performs the request and handles the error */
  async ParticipantsDelete(params: { id: Int }) {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/participants";
    this.startRequest();
    try {
      await Axios.delete(fullUrl, {
        headers: this.getHeaders(),
        params: { id: String(params["id"]) },
      });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** PaiementsCreate performs the request and handles the error */
  async PaiementsCreate(params: { idDossier: Int }) {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/paiements";
    this.startRequest();
    try {
      const rep: AxiosResponse<Paiement> = await Axios.get(fullUrl, {
        headers: this.getHeaders(),
        params: { idDossier: String(params["idDossier"]) },
      });
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** PaiementsUpdate performs the request and handles the error */
  async PaiementsUpdate(params: Paiement) {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/paiements";
    this.startRequest();
    try {
      await Axios.post(fullUrl, params, { headers: this.getHeaders() });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** PaiementsDelete performs the request and handles the error */
  async PaiementsDelete(params: { id: Int }) {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/paiements";
    this.startRequest();
    try {
      await Axios.delete(fullUrl, {
        headers: this.getHeaders(),
        params: { id: String(params["id"]) },
      });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** EventsSendMessage performs the request and handles the error */
  async EventsSendMessage(params: EventsSendMessageIn) {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/events/message";
    this.startRequest();
    try {
      await Axios.post(fullUrl, params, { headers: this.getHeaders() });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** EventsDelete performs the request and handles the error */
  async EventsDelete(params: { id: Int }) {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/events";
    this.startRequest();
    try {
      await Axios.delete(fullUrl, {
        headers: this.getHeaders(),
        params: { id: String(params["id"]) },
      });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** EventsMarkMessagesSeen performs the request and handles the error */
  async EventsMarkMessagesSeen(params: { idDossier: Int }) {
    const fullUrl = this.baseUrl + "/api/v1/backoffice/events/message/seen";
    this.startRequest();
    try {
      await Axios.post(fullUrl, null, {
        headers: this.getHeaders(),
        params: { idDossier: String(params["idDossier"]) },
      });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }
}
