// Code generated by gomacro/typescript/axios_api.go. DO NOT EDIT

import type { AxiosResponse } from "axios";
import Axios from "axios";

export type Ar4_Int = [Int, Int, Int, Int];

// AAAA-MM-YY date format
export type Date_ = string & { __opaque__: "Date" };

export type Int = number & { __opaque__: "Int" };

// ISO date-time string
export type Time = string & { __opaque__: "Time" };

// registro/controllers/espaceperso.Data
export interface Data {
  Dossier: DossierExt;
  IsPaiementOpen: boolean;
}
// registro/controllers/espaceperso.FichesanitaireExt
export interface FichesanitaireExt {
  Personne: string;
  IsLocked: boolean;
  State: FichesanitaireState;
  Fichesanitaire: Fichesanitaire;
  RespoTels: Tels;
  RespoSecuriteSociale: string;
  VaccinsDemande: Demande;
  VaccinsFiles: PublicFile[] | null;
}
// registro/controllers/espaceperso.Joomeo
export interface Joomeo {
  SpaceURL: string;
  Loggin: string;
  Password: string;
  Albums: string[] | null;
}
// registro/controllers/espaceperso.SendMessageIn
export interface SendMessageIn {
  Token: string;
  Message: string;
}
// registro/controllers/espaceperso.SondageExt
export interface SondageExt {
  Camp: string;
  Sondage: Sondage;
}
// registro/controllers/espaceperso.UpdateFichesanitaireIn
export interface UpdateFichesanitaireIn {
  Token: string;
  Fichesanitaire: Fichesanitaire;
  SecuriteSocialeResponsable: string;
}
// registro/controllers/espaceperso.UpdateParticipantsIn
export interface UpdateParticipantsIn {
  Token: string;
  Participants: Participant[] | null;
}
// registro/controllers/espaceperso.UpdateSondageIn
export interface UpdateSondageIn {
  Token: string;
  Id: IdSondage;
  IdCamp: IdCamp;
  Reponse: ReponseSondage;
}
// registro/controllers/files.PublicFile
export interface PublicFile {
  Key: string;
  Id: IdFile;
  Taille: Int;
  NomClient: string;
  Uploaded: Time;
}
// registro/controllers/logic.AideResolved
export interface AideResolved {
  Structure: string;
  Montant: Montant;
}
// registro/controllers/logic.Attestation
export interface Attestation {
  Distribution: Distribution;
  IsPresence: boolean;
}
// registro/controllers/logic.BilanFinancesPub
export interface BilanFinancesPub {
  Inscrits: Record<IdParticipant, BilanParticipantPub> | null;
  Demande: string;
  Aides: string;
  Recu: string;
  Restant: string;
  Statut: StatutPaiement;
}
// registro/controllers/logic.BilanParticipantPub
export interface BilanParticipantPub {
  AvecOption: Montant;
  AvecOptionDescription: string;
  Remises: Remises;
  Aides: AideResolved[] | null;
  AvecAides: string;
  Net: string;
}
// registro/controllers/logic.CampDocs
export interface CampDocs {
  IdCamp: IdCamp;
  CampLabel: string;
}
// registro/controllers/logic.DossierExt
export interface DossierExt {
  Dossier: Dossier;
  Responsable: string;
  Participants: ParticipantCamp[] | null;
  Aides: Record<IdParticipant, Aides> | null;
  AidesFiles: Record<IdAide, PublicFile> | null;
  Events: Events;
  Paiements: Paiements;
  Bilan: BilanFinancesPub;
}
// registro/controllers/logic.Event
export interface Event {
  Id: IdEvent;
  Created: Time;
  Content: EventContent;
}

export const EventContentKind = {
  Attestation: "Attestation",
  CampDocs: "CampDocs",
  Facture: "Facture",
  Message: "Message",
  PlaceLiberee: "PlaceLiberee",
  Sondage: "Sondage",
  Supprime: "Supprime",
  Validation: "Validation",
} as const;
export type EventContentKind =
  (typeof EventContentKind)[keyof typeof EventContentKind];

// registro/controllers/logic.EventContent
export type EventContent =
  | { Kind: "Attestation"; Data: Attestation }
  | { Kind: "CampDocs"; Data: CampDocs }
  | { Kind: "Facture"; Data: Facture }
  | { Kind: "Message"; Data: Message }
  | { Kind: "PlaceLiberee"; Data: PlaceLiberee }
  | { Kind: "Sondage"; Data: Sondage }
  | { Kind: "Supprime"; Data: Supprime }
  | { Kind: "Validation"; Data: Validation };

// registro/controllers/logic.Events
export type Events = Event[] | null;
// registro/controllers/logic.Facture
export type Facture = Record<string, never>;
// registro/controllers/logic.Message
export interface Message {
  Message: EventMessage;
  OrigineCampLabel: string;
  VuParCamps: string[] | null;
}
// registro/controllers/logic.PlaceLiberee
export interface PlaceLiberee {
  IdParticipant: IdParticipant;
  IdCamp: IdCamp;
  ParticipantLabel: string;
  CampLabel: string;
}
// registro/controllers/logic.Sondage
export interface Sondage {
  IdCamp: IdCamp;
  CampLabel: string;
}
// registro/controllers/logic.StatutPaiement
export const StatutPaiement = {
  Complet: 3,
  EnCours: 2,
  NonCommence: 1,
} as const;
export type StatutPaiement =
  (typeof StatutPaiement)[keyof typeof StatutPaiement];

export const StatutPaiementLabels: Record<StatutPaiement, string> = {
  [StatutPaiement.Complet]: "",
  [StatutPaiement.EnCours]: "",
  [StatutPaiement.NonCommence]: "",
};

// registro/controllers/logic.Supprime
export type Supprime = Record<string, never>;
// registro/controllers/logic.Validation
export interface Validation {
  ByCamp: string;
}
// registro/sql/camps.Aide
export interface Aide {
  Id: IdAide;
  IdStructureaide: IdStructureaide;
  IdParticipant: IdParticipant;
  Valide: boolean;
  Valeur: Montant;
  ParJour: boolean;
  NbJoursMax: Int;
}
// registro/sql/camps.Aides
export type Aides = Record<IdAide, Aide> | null;
// registro/sql/camps.Camp
export interface Camp {
  Id: IdCamp;
  IdTaux: IdTaux;
  Nom: string;
  DateDebut: Date;
  Duree: Int;
  Lieu: string;
  Agrement: string;
  ImageURL: string;
  Description: string;
  Navette: OptionNavette;
  Places: Int;
  AgeMin: Int;
  AgeMax: Int;
  NeedEquilibreGF: boolean;
  Ouvert: boolean;
  Prix: Montant;
  OptionPrix: OptionPrixCamp;
  OptionQuotientFamilial: PrixQuotientFamilial;
  Password: string;
  DocumentsReady: boolean;
  DocumentsToShow: DocumentsToShow;
  Vetements: ListeVetements;
}
// registro/sql/camps.DocumentsToShow
export interface DocumentsToShow {
  LettreDirecteur: boolean;
  ListeVetements: boolean;
  ListeParticipants: boolean;
}
export type IdAide = number & { __opaque__: "IdAide" };
export type IdCamp = number & { __opaque__: "IdCamp" };
export type IdParticipant = number & { __opaque__: "IdParticipant" };
export type IdSondage = number & { __opaque__: "IdSondage" };
export type IdStructureaide = number & { __opaque__: "IdStructureaide" };
// registro/sql/camps.Jours
export type Jours = Int[] | null;
// registro/sql/camps.ListeVetements
export interface ListeVetements {
  Vetements: Vetement[] | null;
  Complement: string;
}
// registro/sql/camps.Navette
export const Navette = {
  NoBus: 0,
  Aller: 1,
  Retour: 2,
  AllerRetour: 3,
} as const;
export type Navette = (typeof Navette)[keyof typeof Navette];

export const NavetteLabels: Record<Navette, string> = {
  [Navette.NoBus]: "Aucun trajet",
  [Navette.Aller]: "Aller",
  [Navette.Retour]: "Retour",
  [Navette.AllerRetour]: "Aller-Retour",
};

// registro/sql/camps.OptionNavette
export interface OptionNavette {
  Actif: boolean;
  Commentaire: string;
}
// registro/sql/camps.OptionPrixCamp
export interface OptionPrixCamp {
  Active: OptionPrixKind;
  Statuts: PrixParStatut[] | null;
  Jours: Int[] | null;
}
// registro/sql/camps.OptionPrixKind
export const OptionPrixKind = {
  NoOption: 0,
  PrixStatut: 1,
  PrixJour: 2,
} as const;
export type OptionPrixKind =
  (typeof OptionPrixKind)[keyof typeof OptionPrixKind];

export const OptionPrixKindLabels: Record<OptionPrixKind, string> = {
  [OptionPrixKind.NoOption]: "Aucune",
  [OptionPrixKind.PrixStatut]: "Prix par statut",
  [OptionPrixKind.PrixJour]: "Prix à la journée",
};

// registro/sql/camps.OptionPrixParticipant
export interface OptionPrixParticipant {
  IdStatut: Int;
  Jour: Jours;
}
// registro/sql/camps.Participant
export interface Participant {
  Id: IdParticipant;
  IdCamp: IdCamp;
  IdPersonne: IdPersonne;
  IdDossier: IdDossier;
  IdTaux: IdTaux;
  Statut: StatutParticipant;
  Remises: Remises;
  QuotientFamilial: Int;
  OptionPrix: OptionPrixParticipant;
  Details: string;
  Navette: Navette;
}
// registro/sql/camps.ParticipantCamp
export interface ParticipantCamp {
  Camp: Camp;
  Participant: Participant;
  Personne: Personne;
}
// registro/sql/camps.PrixParStatut
export interface PrixParStatut {
  Id: Int;
  Prix: Int;
  Label: string;
  Description: string;
}
// registro/sql/camps.PrixQuotientFamilial
export type PrixQuotientFamilial = Ar4_Int;
// registro/sql/camps.Remises
export interface Remises {
  ReducEquipiers: Int;
  ReducEnfants: Int;
  ReducSpeciale: Montant;
}
// registro/sql/camps.ReponseSondage
export interface ReponseSondage {
  InfosAvantSejour: Satisfaction;
  InfosPendantSejour: Satisfaction;
  Hebergement: Satisfaction;
  Activites: Satisfaction;
  Theme: Satisfaction;
  Nourriture: Satisfaction;
  Hygiene: Satisfaction;
  Ambiance: Satisfaction;
  Ressenti: Satisfaction;
  MessageEnfant: string;
  MessageResponsable: string;
}
// registro/sql/camps.Satisfaction
export const Satisfaction = {
  NoSatisfaction: 0,
  Decevant: 1,
  Moyen: 2,
  Satisfaisant: 3,
  Tressatisfaisant: 4,
} as const;
export type Satisfaction = (typeof Satisfaction)[keyof typeof Satisfaction];

export const SatisfactionLabels: Record<Satisfaction, string> = {
  [Satisfaction.NoSatisfaction]: "-",
  [Satisfaction.Decevant]: "Décevant",
  [Satisfaction.Moyen]: "Moyen",
  [Satisfaction.Satisfaisant]: "Satisfaisant",
  [Satisfaction.Tressatisfaisant]: "Très satisfaisant",
};

// registro/sql/camps.Sondage
export interface Sondage {
  Id: IdSondage;
  IdCamp: IdCamp;
  IdDossier: IdDossier;
  Modified: Time;
  InfosAvantSejour: Satisfaction;
  InfosPendantSejour: Satisfaction;
  Hebergement: Satisfaction;
  Activites: Satisfaction;
  Theme: Satisfaction;
  Nourriture: Satisfaction;
  Hygiene: Satisfaction;
  Ambiance: Satisfaction;
  Ressenti: Satisfaction;
  MessageEnfant: string;
  MessageResponsable: string;
}
// registro/sql/camps.StatutParticipant
export const StatutParticipant = {
  AStatuer: 0,
  Refuse: 1,
  AttenteProfilInvalide: 2,
  AttenteCampComplet: 3,
  EnAttenteReponse: 4,
  Inscrit: 5,
} as const;
export type StatutParticipant =
  (typeof StatutParticipant)[keyof typeof StatutParticipant];

export const StatutParticipantLabels: Record<StatutParticipant, string> = {
  [StatutParticipant.AStatuer]: "A statuer",
  [StatutParticipant.Refuse]: "Refusé définitivement",
  [StatutParticipant.AttenteProfilInvalide]: "Profil limite",
  [StatutParticipant.AttenteCampComplet]: "Camp complet",
  [StatutParticipant.EnAttenteReponse]: "En attente de réponse",
  [StatutParticipant.Inscrit]: "Inscrit",
};

// registro/sql/camps.Structureaide
export interface Structureaide {
  Id: IdStructureaide;
  Nom: string;
  Immatriculation: string;
  Info: string;
}
// registro/sql/camps.Structureaides
export type Structureaides = Record<IdStructureaide, Structureaide> | null;
// registro/sql/camps.Vetement
export interface Vetement {
  Quantite: Int;
  Description: string;
  Important: boolean;
}
// registro/sql/dossiers.Currency
export const Currency = {
  Euros: 0,
  FrancsSuisse: 1,
} as const;
export type Currency = (typeof Currency)[keyof typeof Currency];

export const CurrencyLabels: Record<Currency, string> = {
  [Currency.Euros]: "€",
  [Currency.FrancsSuisse]: "CHF",
};

// registro/sql/dossiers.Dossier
export interface Dossier {
  Id: IdDossier;
  IdTaux: IdTaux;
  IdResponsable: IdPersonne;
  CopiesMails: Mails;
  PartageAdressesOK: boolean;
  DemandeFondSoutien: boolean;
  IsValidated: boolean;
  MomentInscription: Time;
  LastSeenEspaceperso: Time;
  KeyV1: string;
}
export type IdDossier = number & { __opaque__: "IdDossier" };
export type IdPaiement = number & { __opaque__: "IdPaiement" };
export type IdTaux = number & { __opaque__: "IdTaux" };
// registro/sql/dossiers.ModePaiement
export const ModePaiement = {
  Cheque: 0,
  EnLigne: 1,
  Virement: 2,
  Especes: 3,
  Ancv: 4,
  Helloasso: 5,
} as const;
export type ModePaiement = (typeof ModePaiement)[keyof typeof ModePaiement];

export const ModePaiementLabels: Record<ModePaiement, string> = {
  [ModePaiement.Cheque]: "Chèque",
  [ModePaiement.EnLigne]: "Carte bancaire (en ligne)",
  [ModePaiement.Virement]: "Virement",
  [ModePaiement.Especes]: "Espèces",
  [ModePaiement.Ancv]: "ANCV",
  [ModePaiement.Helloasso]: "Helloasso",
};

// registro/sql/dossiers.Montant
export interface Montant {
  Cent: Int;
  Currency: Currency;
}
// registro/sql/dossiers.Paiement
export interface Paiement {
  Id: IdPaiement;
  IdDossier: IdDossier;
  IsRemboursement: boolean;
  Montant: Montant;
  Payeur: string;
  Mode: ModePaiement;
  Time: Time;
  Label: string;
  Details: string;
}
// registro/sql/dossiers.Paiements
export type Paiements = Record<IdPaiement, Paiement> | null;
// registro/sql/events.Distribution
export const Distribution = {
  DEspacePerso: 0,
  DMail: 1,
  DMailAndDownloaded: 2,
} as const;
export type Distribution = (typeof Distribution)[keyof typeof Distribution];

export const DistributionLabels: Record<Distribution, string> = {
  [Distribution.DEspacePerso]: "Téléchargée depuis l'espace de suivi",
  [Distribution.DMail]: "Notifiée par courriel",
  [Distribution.DMailAndDownloaded]: "Téléchargée après notification",
};

// registro/sql/events.EventMessage
export interface EventMessage {
  IdEvent: IdEvent;
  Contenu: string;
  Origine: MessageOrigine;
  OrigineCamp: OptID_IdCamp;
  VuBackoffice: boolean;
  VuEspaceperso: boolean;
}
export type IdEvent = number & { __opaque__: "IdEvent" };
// registro/sql/events.MessageOrigine
export const MessageOrigine = {
  FromEspaceperso: 0,
  FromBackoffice: 1,
  FromDirecteur: 2,
} as const;
export type MessageOrigine =
  (typeof MessageOrigine)[keyof typeof MessageOrigine];

export const MessageOrigineLabels: Record<MessageOrigine, string> = {
  [MessageOrigine.FromEspaceperso]: "",
  [MessageOrigine.FromBackoffice]: "",
  [MessageOrigine.FromDirecteur]: "",
};

// registro/sql/files.Categorie
export const Categorie = {
  NoBuiltin: 0,
  CarteId: 1,
  Permis: 2,
  SB: 3,
  Secourisme: 4,
  Bafa: 5,
  Bafd: 6,
  CarteVitale: 7,
  Vaccins: 8,
  Haccp: 9,
  BafdEquiv: 10,
  BafaEquiv: 11,
  CertMedicalCuisine: 12,
  Scolarite: 13,
  Autre: 14,
  nbCategorieEquipier: 15,
} as const;
export type Categorie = (typeof Categorie)[keyof typeof Categorie];

export const CategorieLabels: Record<Categorie, string> = {
  [Categorie.NoBuiltin]: "-",
  [Categorie.CarteId]: "Carte d'identité/Passeport",
  [Categorie.Permis]: "Permis de conduire",
  [Categorie.SB]: "Surveillant de baignade",
  [Categorie.Secourisme]: "Secourisme (PSC1 - AFPS)",
  [Categorie.Bafa]: "BAFA",
  [Categorie.Bafd]: "BAFD",
  [Categorie.CarteVitale]: "Carte Vitale",
  [Categorie.Vaccins]: "Vaccins",
  [Categorie.Haccp]: "Cuisine (HACCP)",
  [Categorie.BafdEquiv]: "Equivalent BAFD",
  [Categorie.BafaEquiv]: "Equivalent BAFA",
  [Categorie.CertMedicalCuisine]: "Certificat médical cuisine",
  [Categorie.Scolarite]: "Certificat de scolarité",
  [Categorie.Autre]: "Autre",
  [Categorie.nbCategorieEquipier]: "",
};

// registro/sql/files.Demande
export interface Demande {
  Id: IdDemande;
  IdFile: OptID_IdFile;
  IdDirecteur: OptID_IdPersonne;
  Categorie: Categorie;
  Description: string;
  MaxDocs: Int;
  JoursValide: Int;
}
export type IdDemande = number & { __opaque__: "IdDemande" };
export type IdFile = number & { __opaque__: "IdFile" };
// registro/sql/personnes.Allergies
export interface Allergies {
  Asthme: boolean;
  Alimentaires: boolean;
  Medicamenteuses: boolean;
  Autres: string;
  ConduiteATenir: string;
}
// registro/sql/personnes.Approfondissement
export const Approfondissement = {
  AAucun: 0,
  AAutre: 1,
  ASb: 2,
  ACanoe: 3,
  AVoile: 4,
  AMoto: 5,
} as const;
export type Approfondissement =
  (typeof Approfondissement)[keyof typeof Approfondissement];

export const ApprofondissementLabels: Record<Approfondissement, string> = {
  [Approfondissement.AAucun]: "Non effectué",
  [Approfondissement.AAutre]: "Approfondissement",
  [Approfondissement.ASb]: "Surveillant de baignade",
  [Approfondissement.ACanoe]: "Canoë - Kayak",
  [Approfondissement.AVoile]: "Voile",
  [Approfondissement.AMoto]: "Loisirs motocyclistes",
};

// registro/sql/personnes.Departement
export type Departement = string;
// registro/sql/personnes.Diplome
export const Diplome = {
  DAucun: 0,
  DBafa: 1,
  DBafaStag: 2,
  DBafd: 3,
  DBafdStag: 4,
  DCap: 5,
  DAssSociale: 6,
  DEducSpe: 7,
  DMonEduc: 8,
  DInstit: 9,
  DProf: 10,
  DAgreg: 11,
  DBjeps: 12,
  DDut: 13,
  DEje: 14,
  DDeug: 15,
  DStaps: 16,
  DBapaat: 17,
  DBeatep: 18,
  DZzautre: 19,
} as const;
export type Diplome = (typeof Diplome)[keyof typeof Diplome];

export const DiplomeLabels: Record<Diplome, string> = {
  [Diplome.DAucun]: "Aucun",
  [Diplome.DBafa]: "BAFA Titulaire",
  [Diplome.DBafaStag]: "BAFA Stagiaire",
  [Diplome.DBafd]: "BAFD titulaire",
  [Diplome.DBafdStag]: "BAFD stagiaire",
  [Diplome.DCap]: "CAP petit enfance",
  [Diplome.DAssSociale]: "Assitante Sociale",
  [Diplome.DEducSpe]: "Educ. spé.",
  [Diplome.DMonEduc]: "Moniteur educateur",
  [Diplome.DInstit]: "Professeur des écoles",
  [Diplome.DProf]: "Enseignant du secondaire",
  [Diplome.DAgreg]: "Agrégé",
  [Diplome.DBjeps]: "BPJEPS",
  [Diplome.DDut]: "DUT carrière sociale",
  [Diplome.DEje]: "EJE",
  [Diplome.DDeug]: "DEUG",
  [Diplome.DStaps]: "STAPS",
  [Diplome.DBapaat]: "BAPAAT",
  [Diplome.DBeatep]: "BEATEP",
  [Diplome.DZzautre]: "AUTRE",
};

// registro/sql/personnes.Fichesanitaire
export interface Fichesanitaire {
  IdPersonne: IdPersonne;
  TraitementMedical: boolean;
  Maladies: Maladies;
  Allergies: Allergies;
  DifficultesSante: string;
  Recommandations: string;
  Handicap: boolean;
  Tel: Tel;
  Medecin: Medecin;
  LastModif: Time;
  Mails: Mails;
}
// registro/sql/personnes.FichesanitaireState
export const FichesanitaireState = {
  NoFiche: 0,
  Outdated: 1,
  UpToDate: 2,
} as const;
export type FichesanitaireState =
  (typeof FichesanitaireState)[keyof typeof FichesanitaireState];

export const FichesanitaireStateLabels: Record<FichesanitaireState, string> = {
  [FichesanitaireState.NoFiche]: "Vide",
  [FichesanitaireState.Outdated]: "Pas à jour",
  [FichesanitaireState.UpToDate]: "Remplie",
};

export type IdPersonne = number & { __opaque__: "IdPersonne" };
// registro/sql/personnes.Mails
export type Mails = string[] | null;
// registro/sql/personnes.Maladies
export interface Maladies {
  Rubeole: boolean;
  Varicelle: boolean;
  Angine: boolean;
  Oreillons: boolean;
  Scarlatine: boolean;
  Coqueluche: boolean;
  Otite: boolean;
  Rougeole: boolean;
  Rhumatisme: boolean;
}
// registro/sql/personnes.Medecin
export interface Medecin {
  Nom: string;
  Tel: Tel;
}
// registro/sql/personnes.Nationnalite
export const Nationnalite = {
  Autre: 0,
  Francaise: 1,
  Suisse: 2,
} as const;
export type Nationnalite = (typeof Nationnalite)[keyof typeof Nationnalite];

export const NationnaliteLabels: Record<Nationnalite, string> = {
  [Nationnalite.Autre]: "Autre",
  [Nationnalite.Francaise]: "Française",
  [Nationnalite.Suisse]: "Suisse",
};

// registro/sql/personnes.Pays
export type Pays = string;
// registro/sql/personnes.Personne
export interface Personne {
  Id: IdPersonne;
  Nom: string;
  Prenom: string;
  Sexe: Sexe;
  DateNaissance: Date;
  VilleNaissance: string;
  DepartementNaissance: Departement;
  Nationnalite: Nationnalite;
  Tels: Tels;
  Mail: string;
  Adresse: string;
  CodePostal: string;
  Ville: string;
  Pays: Pays;
  SecuriteSociale: string;
  NomJeuneFille: string;
  Profession: string;
  Etudiant: boolean;
  Fonctionnaire: boolean;
  Diplome: Diplome;
  Approfondissement: Approfondissement;
  Publicite: Publicite;
  IsTemp: boolean;
}
// registro/sql/personnes.Publicite
export interface Publicite {
  VersionPapier: boolean;
  PubHiver: boolean;
  PubEte: boolean;
  EchoRocher: boolean;
  Eonews: boolean;
}
// registro/sql/personnes.Sexe
export const Sexe = {
  NoSexe: 0,
  Woman: 1,
  Man: 2,
} as const;
export type Sexe = (typeof Sexe)[keyof typeof Sexe];

export const SexeLabels: Record<Sexe, string> = {
  [Sexe.NoSexe]: "",
  [Sexe.Woman]: "Femme",
  [Sexe.Man]: "Homme",
};

// registro/sql/personnes.Tel
export type Tel = string;
// registro/sql/personnes.Tels
export type Tels = string[] | null;
// registro/sql/shared.Date
export type Date = Date_;
// registro/sql/shared.OptID[registro/sql/camps.IdCamp]
export interface OptID_IdCamp {
  Id: IdCamp;
  Valid: boolean;
}
// registro/sql/shared.OptID[registro/sql/files.IdFile]
export interface OptID_IdFile {
  Id: IdFile;
  Valid: boolean;
}
// registro/sql/shared.OptID[registro/sql/personnes.IdPersonne]
export interface OptID_IdPersonne {
  Id: IdPersonne;
  Valid: boolean;
}

/** AbstractAPI provides auto-generated API calls and should be used 
		as base class for an app controller.
	*/
export abstract class AbstractAPI {
  constructor(
    protected baseUrl: string,
    protected authToken: string,
  ) {}

  protected abstract handleError(error: any): void;

  protected abstract startRequest(): void;

  getHeaders() {
    return { Authorization: "Bearer " + this.authToken };
  }

  /** Load performs the request and handles the error */
  async Load(params: { token: string }) {
    const fullUrl = this.baseUrl + "/api/v1/espaceperso";
    this.startRequest();
    try {
      const rep: AxiosResponse<Data> = await Axios.get(fullUrl, {
        headers: this.getHeaders(),
        params: { token: params["token"] },
      });
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** SendMessage performs the request and handles the error */
  async SendMessage(params: SendMessageIn) {
    const fullUrl = this.baseUrl + "/api/v1/espaceperso/message";
    this.startRequest();
    try {
      const rep: AxiosResponse<Event> = await Axios.post(fullUrl, params, {
        headers: this.getHeaders(),
      });
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** UpdateParticipants performs the request and handles the error */
  async UpdateParticipants(params: UpdateParticipantsIn) {
    const fullUrl = this.baseUrl + "/api/v1/espaceperso/participants";
    this.startRequest();
    try {
      await Axios.post(fullUrl, params, { headers: this.getHeaders() });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** CreateAide performs the request and handles the error */
  async CreateAide(file: File, formValue: Aide, params: { token: string }) {
    const fullUrl = this.baseUrl + "/api/v1/espaceperso/aide";
    this.startRequest();
    try {
      const formData = new FormData();
      formData.append("document", file, file.name);
      formData.append("aide", JSON.stringify(formValue));
      await Axios.post(fullUrl, formData, {
        headers: this.getHeaders(),
        params: { token: params["token"] },
      });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** GetStructureaides performs the request and handles the error */
  async GetStructureaides() {
    const fullUrl = this.baseUrl + "/api/v1/espaceperso/structureaides";
    this.startRequest();
    try {
      const rep: AxiosResponse<Structureaides> = await Axios.get(fullUrl, {
        headers: this.getHeaders(),
      });
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** LoadJoomeo performs the request and handles the error */
  async LoadJoomeo(params: { token: string }) {
    const fullUrl = this.baseUrl + "/api/v1/espaceperso/joomeo";
    this.startRequest();
    try {
      const rep: AxiosResponse<Joomeo> = await Axios.get(fullUrl, {
        headers: this.getHeaders(),
        params: { token: params["token"] },
      });
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** LoadFichesanitaires performs the request and handles the error */
  async LoadFichesanitaires(params: { token: string }) {
    const fullUrl = this.baseUrl + "/api/v1/espaceperso/fichesanitaires";
    this.startRequest();
    try {
      const rep: AxiosResponse<FichesanitaireExt[] | null> = await Axios.get(
        fullUrl,
        { headers: this.getHeaders(), params: { token: params["token"] } },
      );
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** UpdateFichesanitaire performs the request and handles the error */
  async UpdateFichesanitaire(params: UpdateFichesanitaireIn) {
    const fullUrl = this.baseUrl + "/api/v1/espaceperso/fichesanitaires";
    this.startRequest();
    try {
      await Axios.post(fullUrl, params, { headers: this.getHeaders() });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** UploadVaccin performs the request and handles the error */
  async UploadVaccin(
    file: File,
    params: { token: string; idPersonne: IdPersonne },
  ) {
    const fullUrl = this.baseUrl + "/api/v1/espaceperso/fichesanitaires";
    this.startRequest();
    try {
      const formData = new FormData();
      formData.append("file", file, file.name);
      const rep: AxiosResponse<PublicFile> = await Axios.put(
        fullUrl,
        formData,
        {
          headers: this.getHeaders(),
          params: {
            token: params["token"],
            idPersonne: String(params["idPersonne"]),
          },
        },
      );
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** DeleteVaccin performs the request and handles the error */
  async DeleteVaccin(params: { key: string }) {
    const fullUrl = this.baseUrl + "/api/v1/espaceperso/fichesanitaires";
    this.startRequest();
    try {
      await Axios.delete(fullUrl, {
        headers: this.getHeaders(),
        params: { key: params["key"] },
      });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** TransfertFicheSanitaire performs the request and handles the error */
  async TransfertFicheSanitaire(params: {
    token: string;
    idPersonne: IdPersonne;
  }) {
    const fullUrl =
      this.baseUrl + "/api/v1/espaceperso/fichesanitaires/transfert";
    this.startRequest();
    try {
      await Axios.put(fullUrl, null, {
        headers: this.getHeaders(),
        params: {
          token: params["token"],
          idPersonne: String(params["idPersonne"]),
        },
      });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** LoadSondages performs the request and handles the error */
  async LoadSondages(params: { token: string }) {
    const fullUrl = this.baseUrl + "/api/v1/espaceperso/sondages";
    this.startRequest();
    try {
      const rep: AxiosResponse<SondageExt[] | null> = await Axios.get(fullUrl, {
        headers: this.getHeaders(),
        params: { token: params["token"] },
      });
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** UpdateSondages performs the request and handles the error */
  async UpdateSondages(params: UpdateSondageIn) {
    const fullUrl = this.baseUrl + "/api/v1/espaceperso/sondages";
    this.startRequest();
    try {
      await Axios.post(fullUrl, params, { headers: this.getHeaders() });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }
}
