// Code generated by gomacro/typescript/axios_api.go. DO NOT EDIT

import type { AxiosResponse } from "axios";
import Axios from "axios";

export type Ar4_Int = [Int, Int, Int, Int];

// AAAA-MM-YY date format
export type Date_ = string & { __opaque__: "Date" };

export type Int = number & { __opaque__: "Int" };

// ISO date-time string
export type Time = string & { __opaque__: "Time" };

// registro/controllers/espaceperso.Data
export interface Data {
  Dossier: DossierExt;
}
// registro/controllers/espaceperso.SendMessageIn
export interface SendMessageIn {
  Token: string;
  Message: string;
}
// registro/controllers/espaceperso.UpdateParticipantsIn
export interface UpdateParticipantsIn {
  Token: string;
  Participants: Participant[] | null;
}
// registro/controllers/logic.AideResolved
export interface AideResolved {
  Structure: string;
  Montant: Montant;
}
// registro/controllers/logic.Attestation
export interface Attestation {
  Distribution: Distribution;
  IsPresence: boolean;
}
// registro/controllers/logic.BilanFinancesPub
export interface BilanFinancesPub {
  Inscrits: Record<IdParticipant, BilanParticipantPub> | null;
  Demande: string;
  Aides: string;
  Recu: string;
  Restant: string;
  Statut: StatutPaiement;
}
// registro/controllers/logic.BilanParticipantPub
export interface BilanParticipantPub {
  AvecOption: Montant;
  AvecOptionDescription: string;
  Remises: Remises;
  Aides: AideResolved[] | null;
  AvecAides: string;
  Net: string;
}
// registro/controllers/logic.CampDocs
export interface CampDocs {
  IdCamp: IdCamp;
  CampLabel: string;
}
// registro/controllers/logic.DossierExt
export interface DossierExt {
  Dossier: Dossier;
  Responsable: string;
  Participants: ParticipantCamp[] | null;
  Aides: Record<IdParticipant, Aides> | null;
  Events: Events;
  Paiements: Paiements;
  Bilan: BilanFinancesPub;
}
// registro/controllers/logic.Event
export interface Event {
  Id: IdEvent;
  Created: Time;
  Content: EventContent;
}

export const EventContentKind = {
  Attestation: "Attestation",
  CampDocs: "CampDocs",
  Facture: "Facture",
  Message: "Message",
  PlaceLiberee: "PlaceLiberee",
  Sondage: "Sondage",
  Supprime: "Supprime",
  Validation: "Validation",
} as const;
export type EventContentKind =
  (typeof EventContentKind)[keyof typeof EventContentKind];

// registro/controllers/logic.EventContent
export type EventContent =
  | { Kind: "Attestation"; Data: Attestation }
  | { Kind: "CampDocs"; Data: CampDocs }
  | { Kind: "Facture"; Data: Facture }
  | { Kind: "Message"; Data: Message }
  | { Kind: "PlaceLiberee"; Data: PlaceLiberee }
  | { Kind: "Sondage"; Data: Sondage }
  | { Kind: "Supprime"; Data: Supprime }
  | { Kind: "Validation"; Data: Validation };

// registro/controllers/logic.Events
export type Events = Event[] | null;
// registro/controllers/logic.Facture
export type Facture = Record<string, never>;
// registro/controllers/logic.Message
export interface Message {
  Message: EventMessage;
  OrigineCampLabel: string;
  VuParCamps: string[] | null;
}
// registro/controllers/logic.PlaceLiberee
export interface PlaceLiberee {
  IdParticipant: IdParticipant;
  IdCamp: IdCamp;
  ParticipantLabel: string;
  CampLabel: string;
}
// registro/controllers/logic.Sondage
export interface Sondage {
  IdCamp: IdCamp;
  CampLabel: string;
}
// registro/controllers/logic.StatutPaiement
export const StatutPaiement = {
  Complet: 3,
  EnCours: 2,
  NonCommence: 1,
} as const;
export type StatutPaiement =
  (typeof StatutPaiement)[keyof typeof StatutPaiement];

export const StatutPaiementLabels: Record<StatutPaiement, string> = {
  [StatutPaiement.Complet]: "",
  [StatutPaiement.EnCours]: "",
  [StatutPaiement.NonCommence]: "",
};

// registro/controllers/logic.Supprime
export type Supprime = Record<string, never>;
// registro/controllers/logic.Validation
export interface Validation {
  ByCamp: string;
}
// registro/sql/camps.Aide
export interface Aide {
  Id: IdAide;
  IdStructureaide: IdStructureaide;
  IdParticipant: IdParticipant;
  Valide: boolean;
  Valeur: Montant;
  ParJour: boolean;
  NbJoursMax: Int;
}
// registro/sql/camps.Aides
export type Aides = Record<IdAide, Aide> | null;
// registro/sql/camps.Camp
export interface Camp {
  Id: IdCamp;
  IdTaux: IdTaux;
  Nom: string;
  DateDebut: Date;
  Duree: Int;
  Lieu: string;
  Agrement: string;
  Description: string;
  Navette: OptionNavette;
  Places: Int;
  AgeMin: Int;
  AgeMax: Int;
  NeedEquilibreGF: boolean;
  Ouvert: boolean;
  Prix: Montant;
  OptionPrix: OptionPrixCamp;
  OptionQuotientFamilial: PrixQuotientFamilial;
  Password: string;
}
export type IdAide = number & { __opaque__: "IdAide" };
export type IdCamp = number & { __opaque__: "IdCamp" };
export type IdParticipant = number & { __opaque__: "IdParticipant" };
export type IdStructureaide = number & { __opaque__: "IdStructureaide" };
// registro/sql/camps.Jours
export type Jours = Int[] | null;
// registro/sql/camps.Navette
export const Navette = {
  NoBus: 0,
  Aller: 1,
  Retour: 2,
  AllerRetour: 3,
} as const;
export type Navette = (typeof Navette)[keyof typeof Navette];

export const NavetteLabels: Record<Navette, string> = {
  [Navette.NoBus]: "Aucun trajet",
  [Navette.Aller]: "Aller",
  [Navette.Retour]: "Retour",
  [Navette.AllerRetour]: "Aller-Retour",
};

// registro/sql/camps.OptionNavette
export interface OptionNavette {
  Actif: boolean;
  Commentaire: string;
}
// registro/sql/camps.OptionPrixCamp
export interface OptionPrixCamp {
  Active: OptionPrixKind;
  Statuts: PrixParStatut[] | null;
  Jours: Int[] | null;
}
// registro/sql/camps.OptionPrixKind
export const OptionPrixKind = {
  NoOption: 0,
  PrixStatut: 1,
  PrixJour: 2,
} as const;
export type OptionPrixKind =
  (typeof OptionPrixKind)[keyof typeof OptionPrixKind];

export const OptionPrixKindLabels: Record<OptionPrixKind, string> = {
  [OptionPrixKind.NoOption]: "Aucune",
  [OptionPrixKind.PrixStatut]: "Prix par statut",
  [OptionPrixKind.PrixJour]: "Prix à la journée",
};

// registro/sql/camps.OptionPrixParticipant
export interface OptionPrixParticipant {
  IdStatut: Int;
  Jour: Jours;
}
// registro/sql/camps.Participant
export interface Participant {
  Id: IdParticipant;
  IdCamp: IdCamp;
  IdPersonne: IdPersonne;
  IdDossier: IdDossier;
  IdTaux: IdTaux;
  Statut: StatutParticipant;
  Remises: Remises;
  QuotientFamilial: Int;
  OptionPrix: OptionPrixParticipant;
  Details: string;
  Navette: Navette;
}
// registro/sql/camps.ParticipantCamp
export interface ParticipantCamp {
  Camp: Camp;
  Participant: Participant;
  Personne: Personne;
}
// registro/sql/camps.PrixParStatut
export interface PrixParStatut {
  Id: Int;
  Prix: Int;
  Label: string;
  Description: string;
}
// registro/sql/camps.PrixQuotientFamilial
export type PrixQuotientFamilial = Ar4_Int;
// registro/sql/camps.Remises
export interface Remises {
  ReducEquipiers: Int;
  ReducEnfants: Int;
  ReducSpeciale: Montant;
}
// registro/sql/camps.StatutParticipant
export const StatutParticipant = {
  AStatuer: 0,
  Refuse: 1,
  AttenteProfilInvalide: 2,
  AttenteCampComplet: 3,
  EnAttenteReponse: 4,
  Inscrit: 5,
} as const;
export type StatutParticipant =
  (typeof StatutParticipant)[keyof typeof StatutParticipant];

export const StatutParticipantLabels: Record<StatutParticipant, string> = {
  [StatutParticipant.AStatuer]: "A statuer",
  [StatutParticipant.Refuse]: "Refusé définitivement",
  [StatutParticipant.AttenteProfilInvalide]: "Profil limite",
  [StatutParticipant.AttenteCampComplet]: "Camp complet",
  [StatutParticipant.EnAttenteReponse]: "En attente de réponse",
  [StatutParticipant.Inscrit]: "Inscrit",
};

// registro/sql/dossiers.Currency
export const Currency = {
  Euros: 0,
  FrancsSuisse: 1,
} as const;
export type Currency = (typeof Currency)[keyof typeof Currency];

export const CurrencyLabels: Record<Currency, string> = {
  [Currency.Euros]: "€",
  [Currency.FrancsSuisse]: "CHF",
};

// registro/sql/dossiers.Dossier
export interface Dossier {
  Id: IdDossier;
  IdTaux: IdTaux;
  IdResponsable: IdPersonne;
  CopiesMails: Mails;
  PartageAdressesOK: boolean;
  DemandeFondSoutien: boolean;
  IsValidated: boolean;
  MomentInscription: Time;
  LastSeenEspaceperso: Time;
  KeyV1: string;
}
export type IdDossier = number & { __opaque__: "IdDossier" };
export type IdPaiement = number & { __opaque__: "IdPaiement" };
export type IdTaux = number & { __opaque__: "IdTaux" };
// registro/sql/dossiers.ModePaiement
export const ModePaiement = {
  Cheque: 0,
  EnLigne: 1,
  Virement: 2,
  Especes: 3,
  Ancv: 4,
  Helloasso: 5,
} as const;
export type ModePaiement = (typeof ModePaiement)[keyof typeof ModePaiement];

export const ModePaiementLabels: Record<ModePaiement, string> = {
  [ModePaiement.Cheque]: "Chèque",
  [ModePaiement.EnLigne]: "Carte bancaire (en ligne)",
  [ModePaiement.Virement]: "Virement",
  [ModePaiement.Especes]: "Espèces",
  [ModePaiement.Ancv]: "ANCV",
  [ModePaiement.Helloasso]: "Helloasso",
};

// registro/sql/dossiers.Montant
export interface Montant {
  Cent: Int;
  Currency: Currency;
}
// registro/sql/dossiers.Paiement
export interface Paiement {
  Id: IdPaiement;
  IdDossier: IdDossier;
  IsRemboursement: boolean;
  Montant: Montant;
  Payeur: string;
  Mode: ModePaiement;
  Time: Time;
  Label: string;
  Details: string;
}
// registro/sql/dossiers.Paiements
export type Paiements = Record<IdPaiement, Paiement> | null;
// registro/sql/events.Distribution
export const Distribution = {
  DEspacePerso: 0,
  DMail: 1,
  DMailAndDownloaded: 2,
} as const;
export type Distribution = (typeof Distribution)[keyof typeof Distribution];

export const DistributionLabels: Record<Distribution, string> = {
  [Distribution.DEspacePerso]: "Téléchargée depuis l'espace de suivi",
  [Distribution.DMail]: "Notifiée par courriel",
  [Distribution.DMailAndDownloaded]: "Téléchargée après notification",
};

// registro/sql/events.EventMessage
export interface EventMessage {
  IdEvent: IdEvent;
  Contenu: string;
  Origine: MessageOrigine;
  OrigineCamp: OptID_IdCamp;
  VuBackoffice: boolean;
  VuEspaceperso: boolean;
}
export type IdEvent = number & { __opaque__: "IdEvent" };
// registro/sql/events.MessageOrigine
export const MessageOrigine = {
  FromEspaceperso: 0,
  FromBackoffice: 1,
  FromDirecteur: 2,
} as const;
export type MessageOrigine =
  (typeof MessageOrigine)[keyof typeof MessageOrigine];

export const MessageOrigineLabels: Record<MessageOrigine, string> = {
  [MessageOrigine.FromEspaceperso]: "",
  [MessageOrigine.FromBackoffice]: "",
  [MessageOrigine.FromDirecteur]: "",
};

// registro/sql/personnes.Approfondissement
export const Approfondissement = {
  AAucun: 0,
  AAutre: 1,
  ASb: 2,
  ACanoe: 3,
  AVoile: 4,
  AMoto: 5,
} as const;
export type Approfondissement =
  (typeof Approfondissement)[keyof typeof Approfondissement];

export const ApprofondissementLabels: Record<Approfondissement, string> = {
  [Approfondissement.AAucun]: "Non effectué",
  [Approfondissement.AAutre]: "Approfondissement",
  [Approfondissement.ASb]: "Surveillant de baignade",
  [Approfondissement.ACanoe]: "Canoë - Kayak",
  [Approfondissement.AVoile]: "Voile",
  [Approfondissement.AMoto]: "Loisirs motocyclistes",
};

// registro/sql/personnes.Departement
export type Departement = string;
// registro/sql/personnes.Diplome
export const Diplome = {
  DAucun: 0,
  DBafa: 1,
  DBafaStag: 2,
  DBafd: 3,
  DBafdStag: 4,
  DCap: 5,
  DAssSociale: 6,
  DEducSpe: 7,
  DMonEduc: 8,
  DInstit: 9,
  DProf: 10,
  DAgreg: 11,
  DBjeps: 12,
  DDut: 13,
  DEje: 14,
  DDeug: 15,
  DStaps: 16,
  DBapaat: 17,
  DBeatep: 18,
  DZzautre: 19,
} as const;
export type Diplome = (typeof Diplome)[keyof typeof Diplome];

export const DiplomeLabels: Record<Diplome, string> = {
  [Diplome.DAucun]: "Aucun",
  [Diplome.DBafa]: "BAFA Titulaire",
  [Diplome.DBafaStag]: "BAFA Stagiaire",
  [Diplome.DBafd]: "BAFD titulaire",
  [Diplome.DBafdStag]: "BAFD stagiaire",
  [Diplome.DCap]: "CAP petit enfance",
  [Diplome.DAssSociale]: "Assitante Sociale",
  [Diplome.DEducSpe]: "Educ. spé.",
  [Diplome.DMonEduc]: "Moniteur educateur",
  [Diplome.DInstit]: "Professeur des écoles",
  [Diplome.DProf]: "Enseignant du secondaire",
  [Diplome.DAgreg]: "Agrégé",
  [Diplome.DBjeps]: "BPJEPS",
  [Diplome.DDut]: "DUT carrière sociale",
  [Diplome.DEje]: "EJE",
  [Diplome.DDeug]: "DEUG",
  [Diplome.DStaps]: "STAPS",
  [Diplome.DBapaat]: "BAPAAT",
  [Diplome.DBeatep]: "BEATEP",
  [Diplome.DZzautre]: "AUTRE",
};

export type IdPersonne = number & { __opaque__: "IdPersonne" };
// registro/sql/personnes.Mails
export type Mails = string[] | null;
// registro/sql/personnes.Nationnalite
export const Nationnalite = {
  Autre: 0,
  Francaise: 1,
  Suisse: 2,
} as const;
export type Nationnalite = (typeof Nationnalite)[keyof typeof Nationnalite];

export const NationnaliteLabels: Record<Nationnalite, string> = {
  [Nationnalite.Autre]: "Autre",
  [Nationnalite.Francaise]: "Française",
  [Nationnalite.Suisse]: "Suisse",
};

// registro/sql/personnes.Pays
export type Pays = string;
// registro/sql/personnes.Personne
export interface Personne {
  Id: IdPersonne;
  Nom: string;
  Prenom: string;
  Sexe: Sexe;
  DateNaissance: Date;
  VilleNaissance: string;
  DepartementNaissance: Departement;
  Nationnalite: Nationnalite;
  Tels: Tels;
  Mail: string;
  Adresse: string;
  CodePostal: string;
  Ville: string;
  Pays: Pays;
  SecuriteSociale: string;
  NomJeuneFille: string;
  Profession: string;
  Etudiant: boolean;
  Fonctionnaire: boolean;
  Diplome: Diplome;
  Approfondissement: Approfondissement;
  Publicite: Publicite;
  IsTemp: boolean;
}
// registro/sql/personnes.Publicite
export interface Publicite {
  VersionPapier: boolean;
  PubHiver: boolean;
  PubEte: boolean;
  EchoRocher: boolean;
  Eonews: boolean;
}
// registro/sql/personnes.Sexe
export const Sexe = {
  Empty: 0,
  Woman: 1,
  Man: 2,
} as const;
export type Sexe = (typeof Sexe)[keyof typeof Sexe];

export const SexeLabels: Record<Sexe, string> = {
  [Sexe.Empty]: "",
  [Sexe.Woman]: "Femme",
  [Sexe.Man]: "Homme",
};

// registro/sql/personnes.Tels
export type Tels = string[] | null;
// registro/sql/shared.Date
export type Date = Date_;
// registro/sql/shared.OptID[registro/sql/camps.IdCamp]
export interface OptID_IdCamp {
  Id: IdCamp;
  Valid: boolean;
}

/** AbstractAPI provides auto-generated API calls and should be used 
		as base class for an app controller.
	*/
export abstract class AbstractAPI {
  constructor(
    protected baseUrl: string,
    protected authToken: string,
  ) {}

  protected abstract handleError(error: any): void;

  protected abstract startRequest(): void;

  getHeaders() {
    return { Authorization: "Bearer " + this.authToken };
  }

  /** Load performs the request and handles the error */
  async Load(params: { token: string }) {
    const fullUrl = this.baseUrl + "/api/v1/espaceperso";
    this.startRequest();
    try {
      const rep: AxiosResponse<Data> = await Axios.get(fullUrl, {
        headers: this.getHeaders(),
        params: { token: params["token"] },
      });
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** SendMessage performs the request and handles the error */
  async SendMessage(params: SendMessageIn) {
    const fullUrl = this.baseUrl + "/api/v1/espaceperso/message";
    this.startRequest();
    try {
      const rep: AxiosResponse<Event> = await Axios.post(fullUrl, params, {
        headers: this.getHeaders(),
      });
      return rep.data;
    } catch (error) {
      this.handleError(error);
    }
  }

  /** UpdateParticipants performs the request and handles the error */
  async UpdateParticipants(params: UpdateParticipantsIn) {
    const fullUrl = this.baseUrl + "/api/v1/espaceperso/participants";
    this.startRequest();
    try {
      await Axios.post(fullUrl, params, { headers: this.getHeaders() });
      return true;
    } catch (error) {
      this.handleError(error);
    }
  }
}
