// Code generated by gomacro/typescript/axios_api.go. DO NOT EDIT

import type { AxiosResponse } from "axios";
import Axios from "axios";

export type Ar4_Int = [Int, Int, Int, Int];

// AAAA-MM-YY date format
export type Date_ = string & { __opaque__: "Date" };

export type Int = number & { __opaque__: "Int" };
// registro/controllers/inscriptions.DataInscription
export interface DataInscription {
  Camps: Camps;
  InitialInscription: Inscription;
  PreselectedCamp: string;
}
// registro/controllers/inscriptions.Inscription
export interface Inscription {
  Responsable: ResponsableLegal;
  ResponsablePreIdent: string;
  Message: string;
  CopiesMails: Mails;
  PartageAdressesOK: boolean;
  DemandeFondSoutien: boolean;
  Participants: Participant[] | null;
}
// registro/controllers/inscriptions.Participant
export interface Participant {
  PreIdent: string;
  IdCamp: IdCamp;
  Nom: string;
  Prenom: string;
  DateNaissance: Date;
  Sexe: Sexe;
  Nationnalite: Nationnalite;
}
// registro/controllers/inscriptions.SearchHistoryOut
export interface SearchHistoryOut {
  MailFound: boolean;
}
// registro/sql/camps.Camp
export interface Camp {
  Id: IdCamp;
  IdTaux: IdTaux;
  Nom: string;
  DateDebut: Date;
  Duree: Int;
  Lieu: string;
  Agrement: string;
  Description: string;
  Navette: Navette;
  Places: Int;
  AgeMin: Int;
  AgeMax: Int;
  Ouvert: boolean;
  Prix: Montant;
  OptionPrix: OptionPrixCamp;
  OptionQuotientFamilial: OptionQuotientFamilial;
  Password: string;
}
// registro/sql/camps.Camps
export type Camps = { [key in IdCamp]: Camp } | null;
// registro/sql/camps.IdCamp
export type IdCamp = Int;
// registro/sql/camps.Navette
export interface Navette {
  Actif: boolean;
  Commentaire: string;
}
// registro/sql/camps.OptionPrixCamp
export interface OptionPrixCamp {
  Active: OptionPrixKind;
  Semaine: OptionSemaineCamp;
  Statuts: PrixParStatut[] | null;
  Jour: Montant[] | null;
}
// registro/sql/camps.OptionPrixKind
export const OptionPrixKind = {
  NoOption: 0,
  PrixSemaine: 1,
  PrixStatut: 2,
  PrixJour: 3,
} as const;
export type OptionPrixKind =
  (typeof OptionPrixKind)[keyof typeof OptionPrixKind];

export const OptionPrixKindLabels: { [key in OptionPrixKind]: string } = {
  [OptionPrixKind.NoOption]: "",
  [OptionPrixKind.PrixSemaine]: "",
  [OptionPrixKind.PrixStatut]: "",
  [OptionPrixKind.PrixJour]: "",
};

// registro/sql/camps.OptionQuotientFamilial
export type OptionQuotientFamilial = Ar4_Int;
// registro/sql/camps.OptionSemaineCamp
export interface OptionSemaineCamp {
  Plage1: Plage;
  Plage2: Plage;
  Prix1: Montant;
  Prix2: Montant;
}
// registro/sql/camps.PrixParStatut
export interface PrixParStatut {
  Id: Int;
  Prix: Montant;
  Statut: string;
  Description: string;
}
// registro/sql/dossiers.Currency
export const Currency = {
  Euros: 0,
  FrancsSuisse: 1,
} as const;
export type Currency = (typeof Currency)[keyof typeof Currency];

export const CurrencyLabels: { [key in Currency]: string } = {
  [Currency.Euros]: "€",
  [Currency.FrancsSuisse]: "CHF",
};

// registro/sql/dossiers.IdTaux
export type IdTaux = Int;
// registro/sql/dossiers.Montant
export interface Montant {
  Cent: Int;
  Currency: Currency;
}
// registro/sql/inscriptions.ResponsableLegal
export interface ResponsableLegal {
  Nom: string;
  Prenom: string;
  DateNaissance: Date;
  Sexe: Sexe;
  Mail: string;
  Tels: Tels;
  Adresse: string;
  CodePostal: string;
  Ville: string;
  Pays: Pays;
}
// registro/sql/personnes.Mails
export type Mails = string[] | null;
// registro/sql/personnes.Nationnalite
export const Nationnalite = {
  Autre: 0,
  Francaise: 1,
  Suisse: 2,
} as const;
export type Nationnalite = (typeof Nationnalite)[keyof typeof Nationnalite];

export const NationnaliteLabels: { [key in Nationnalite]: string } = {
  [Nationnalite.Autre]: "",
  [Nationnalite.Francaise]: "",
  [Nationnalite.Suisse]: "",
};

// registro/sql/personnes.Pays
export type Pays = string;
// registro/sql/personnes.Sexe
export const Sexe = {
  Empty: 0,
  Woman: 1,
  Man: 2,
} as const;
export type Sexe = (typeof Sexe)[keyof typeof Sexe];

export const SexeLabels: { [key in Sexe]: string } = {
  [Sexe.Empty]: "",
  [Sexe.Woman]: "",
  [Sexe.Man]: "",
};

// registro/sql/personnes.Tels
export type Tels = string[] | null;
// registro/sql/shared.Date
export type Date = Date_;
// registro/sql/shared.Plage
export interface Plage {
  From: Date;
  Duree: Int;
}

/** AbstractAPI provides auto-generated API calls and should be used 
		as base class for an app controller.
	*/
export abstract class AbstractAPI {
  constructor(
    protected baseUrl: string,
    protected authToken: string,
  ) {}

  protected abstract handleError(error: any): void;

  protected abstract startRequest(): void;

  getHeaders() {
    return { Authorization: "Bearer " + this.authToken };
  }

  protected async rawLoadData(params: {
    preselected: string;
    preinscription: string;
  }) {
    const fullUrl = this.baseUrl + "/inscription/v1/load";
    const rep: AxiosResponse<DataInscription> = await Axios.get(fullUrl, {
      headers: this.getHeaders(),
      params: {
        preselected: params["preselected"],
        preinscription: params["preinscription"],
      },
    });
    return rep.data;
  }

  /** LoadData wraps rawLoadData and handles the error */
  async LoadData(params: { preselected: string; preinscription: string }) {
    this.startRequest();
    try {
      const out = await this.rawLoadData(params);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected async rawSaveInscription(params: Inscription) {
    const fullUrl = this.baseUrl + "/inscription/v1/save";
    await Axios.put(fullUrl, params, { headers: this.getHeaders() });
    return true;
  }

  /** SaveInscription wraps rawSaveInscription and handles the error */
  async SaveInscription(params: Inscription) {
    this.startRequest();
    try {
      const out = await this.rawSaveInscription(params);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected async rawSearchHistory(params: { mail: string }) {
    const fullUrl = this.baseUrl + "/inscription/v1/search";
    const rep: AxiosResponse<SearchHistoryOut> = await Axios.get(fullUrl, {
      headers: this.getHeaders(),
      params: { mail: params["mail"] },
    });
    return rep.data;
  }

  /** SearchHistory wraps rawSearchHistory and handles the error */
  async SearchHistory(params: { mail: string }) {
    this.startRequest();
    try {
      const out = await this.rawSearchHistory(params);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }

  protected async rawConfirmeInscription(params: { "insc-token": string }) {
    const fullUrl = this.baseUrl + "/inscription/confirme";
    await Axios.get(fullUrl, {
      headers: this.getHeaders(),
      params: { "insc-token": params["insc-token"] },
    });
    return true;
  }

  /** ConfirmeInscription wraps rawConfirmeInscription and handles the error */
  async ConfirmeInscription(params: { "insc-token": string }) {
    this.startRequest();
    try {
      const out = await this.rawConfirmeInscription(params);
      return out;
    } catch (error) {
      this.handleError(error);
    }
  }
}
